using System;
using UnityEngine;

public class Localize : MonoBehaviour
{
	public static string GetText(string str, string defaultText = null)
	{
		for (int i = 0; i < Localize._Records.Length; i += 3)
		{
			if (Localize._Records[i] == str)
			{
				return Localize._Records[(int)(i + Localize.Locale + 1)];
			}
		}
		return (defaultText == null) ? str : defaultText;
	}

	public static string GetMonth(int month_count, Localize.MounthCase mc)
	{
		if (mc == Localize.MounthCase.ACCUSATIVE)
		{
			return Localize.GetText("GAME_MONTH_ACCUSATIVE", null).Split(new char[]
			{
				','
			})[month_count];
		}
		return string.Empty;
	}

	public static Localize.LocaleType Locale = Localize.LocaleType.EN;

	private static string[] _Records = new string[]
	{
		"Голодные игры!",
		"Голодные игры!",
		"Hunger Games!",
		"ш - инвентарь",
		"ш - инвентарь",
		"i - inventar",
		"ищите сундуки!",
		"ищите сундуки!",
		"look for chests!",
		"ВАША ЦЕЛЬ:",
		"ВАША ЦЕЛЬ:",
		"Your goal:",
		"ВЫЖИТЬ!",
		"ВЫЖИТЬ!",
		"SURVIVE!",
		"В сундуках находится",
		"В сундуках находится",
		"The chests are",
		"Оружие, Броня и Еда",
		"Оружие, Броня и Еда",
		"Weapons, Armor and Food",
		"Голодные игры",
		"Голодные игры",
		"Hunger Games",
		"8 человек",
		"8 человек",
		"8 players",
		"7 трупов",
		"7 трупов",
		"7 dead",
		"1 победитель",
		"1 победитель",
		"1 winner",
		"Сторожевая",
		"Сторожевая",
		"Watch",
		"Ждите пока на сервере",
		"Ждите пока на сервере",
		"Wait until the server",
		"собирёться 8 человек",
		"соберется 8 человек",
		"will gather 8 people",
		"для начала игры",
		"для начала игры",
		"to start the game",
		"Дом",
		"Дом",
		"House",
		"Алхимика",
		"Алхимика",
		"Alchemist",
		"Кузня",
		"Кузня",
		"Forge",
		"SERVERS_TITLE1",
		"СПИСОК СЕРВЕРОВ",
		"MAPS LIST",
		"WIP",
		"В разработке...",
		"Work in progress...",
		"PROFILE_PLAY1",
		"В игре c ",
		"In game ",
		"PROFILE_PLAY2",
		" года",
		" year",
		"PROFILE_STAT_BLOCK1",
		"Командный Бой",
		"Team Battle",
		"PROFILE_STAT_1_1",
		"Количество убийств",
		"Number of kills",
		"PROFILE_STAT_1_2",
		"Количество смертей",
		"Number of deaths",
		"PROFILE_STAT_1_3",
		"Боевая эффективность",
		"Combat effectiveness",
		"PROFILE_STAT_1_4",
		"Количество побед",
		"Number of wins",
		"PROFILE_STAT_BLOCK2",
		"Голодные игры",
		"Hunger Games",
		"PROFILE_STAT_2_1",
		"Количество убийств",
		"Number of kills",
		"PROFILE_STAT_2_2",
		"Количество смертей",
		"Number of deaths",
		"PROFILE_STAT_2_3",
		"Боевая эффективность",
		"Combat effectiveness",
		"PROFILE_STAT_2_4",
		"Количество побед",
		"Number of wins",
		"PROFILE_STAT_BLOCK3",
		"Строительство",
		"Building",
		"PROFILE_STAT_3_1",
		"Построенно блоков",
		"Blocks builded",
		"PROFILE_STAT_3_2",
		"Разрушено блоков",
		"Blocks destroyed",
		"PROFILE_STAT_3_3",
		"Голоса за карты",
		"Votes for maps",
		"PROFILE_STAT_BLOCK4",
		"Беги",
		"Run",
		"PROFILE_STAT_4_1",
		"Количество побед",
		"Number of wins",
		"PROFILE_STAT_4_2",
		"Количество смертей",
		"Number of deaths",
		"PROFILE_STAT_4_3",
		"Эффективность",
		"Effectiveness",
		"REQUIRED_LEVEL",
		"Требуемый уровень: ",
		"Required level: ",
		"REQUIRED_PURCHASE",
		"Требуемая покупка:\n",
		"Required purchase:\n",
		"ENTER_FAIL",
		"Такого сочетания почты и пароля не найдено!",
		"This combination of email and password not found!",
		"ENTER_ERROR",
		"Ошибка:",
		"Error:",
		"REGISTER_WRONG_EMAIL",
		"Некорректный адрес почтового ящика!",
		"Invalid name of the mailbox!",
		"REGISTER_SEND_FAIL",
		"Не удалось выслать письмо на почтовый ящик!",
		"Failed to send the email to the mailbox!",
		"REGISTER_EMAIL_FAILED",
		"Аккаунт на эту почту уже зарегестрирован!",
		"Account for this mailbox is already registered!",
		"REGISTER_REG_FAILED",
		"С вашего компьютера уже зарегестрирован аккаунт!",
		"From your computer has registered an account",
		"RECOVER_SEND",
		"Ваш пароль выслан на почту",
		"Your password is sent to the mailbox",
		"RECOVER_WRONG_EMAIL",
		"Некорректный адрес почтового ящика!",
		"Invalid name of the mailbox!",
		"RECOVER_SEND_FAIL",
		"Не удалось выслать пароль на почтовый ящик!",
		"Unable to send the password to your mailbox!",
		"RECOVER_EMAIL_NOT_FOUND",
		"На данную почту не зарегестирован аккаунт!",
		"On this mailbox account is not registered!",
		"RECOVER_ERROR",
		"Ошибка:",
		"Error:",
		"ACTIVATION_CHECK",
		"На ваш почтовый ящик выслано письмо с инструкцией по активации аккаунта.",
		"On your mailbox sent an email with instructions on how to activate account.",
		"ACTIVATION_REQUIRED",
		"Необходима активация аккаунта.",
		"Account activation is required.",
		"TUTORIAL_TITLE",
		"ОБУЧЕНИЕ",
		"TUTORIAL",
		"WELCOME_REMEMBER",
		"ЗАПОМНИТЬ",
		"REMEMBER",
		"WELCOME_PASSWORD",
		"ПАРОЛЬ:",
		"PASSWORD:",
		"WELCOME_REPEAT_PASSWORD",
		"ПОВТОРИТЕ ПАРОЛЬ:",
		"REPEAT PASSWORD:",
		"WELCOME_LOGIN",
		"ЭЛЕКТРОННАЯ ПОЧТА:",
		"EMAIL:",
		"WELCOME_TITLE",
		"ДОБРО ПОЖАЛОВАТЬ!",
		"WELCOME!",
		"WELCOME_REGISTRATION",
		"РЕГИСТРАЦИЯ",
		"REGISTRATION",
		"WELCOME_ENTER",
		"ВОЙТИ",
		"ENTER",
		"WELOCME_RECOVER",
		"ВОССТАНОВИТЬ",
		"RECOVER",
		"WELCOME_BACK",
		"НАЗАД",
		"BACK",
		"WELOCME_REGISTER",
		"ЗАРЕГИСТРИРОВАТЬСЯ",
		"REGISTER",
		"WELCOME_REGISTRATION_TITLE",
		"ЗАПОЛНИТЕ ПОЛЯ РЕГИСТРАЦИИ",
		"FILL REGISTRATION FILEDS",
		"LOADING_TITLE",
		"ЗАГРУЗКА...",
		"LOADING...",
		"LOADING_WAIT",
		"Ждите",
		"Wait",
		"LOADING_PROFILE",
		"Загрузка профиля",
		"Loading profile",
		"LOADING_LEVEL",
		"Загрузка уровня",
		"Loading level",
		"LOADING_SECURITY_ERROR",
		"Ошибка безопасности",
		"Security error",
		"LOADING_LANDSCAPE_GENERATION",
		"Генерация ландшафта",
		"Landscape generation",
		"LOADING_DECORATIONS_GENERATION",
		"Заселение мира",
		"Decorations generation",
		"LOADING_LANDSCAPE_LIGHTING",
		"Освещение ландшафта",
		"Landscape lighting",
		"LOADING_MAP_CREATION",
		"Создание карты",
		"Map creation",
		"LOADING_LOADING",
		"Загрузка",
		"Loading",
		"LOADING_GET_SHARDS",
		"Получение информации о сервере",
		"Waiting information about server",
		"LOADING_CONNECT_TO_SERVER",
		"Присоединение к серверу",
		"Connect to server",
		"LOADING_BANNED",
		"Вы забаненны",
		"You are banned",
		"LOADING_SERVER",
		"Загрузка сервера",
		"Loading server",
		"LOADING_ENTER_TO_GAME",
		"Вход в игру",
		"Enter to game",
		"LOADING_PASSWORD_RECOVERING",
		"Восстановление пароля",
		"Password recovering",
		"LOADING_PLAYER_REGISTRATION",
		"Регистрация игрока",
		"Player registration",
		"LOADING_TRY_CONNECT",
		"Попытка присоединиться",
		"Trying to connect",
		"LOADING_LEAVING",
		"Выходим",
		"Leaving",
		"LOADING_NAME_CHANGING",
		"Смена имени",
		"Name changing",
		"LOADING_SAVING_MAP",
		"Сохраняем карту",
		"Saving map",
		"LOADING_WAIT_ROOMS",
		"Ожидание списка игр",
		"Waiting list of games",
		"SERVER_SELECT_TITLE1",
		"ВЫБОР СЕРВЕРА",
		"SERVER SELECTION",
		"SERVER_SELECT_TITLE2",
		"РАЗНИЦА ЛИШЬ В СОСТАВЕ ИГРОКОВ",
		"DIFFERENCE ONLY IN PLAYERS COUNT",
		"SERVER_SELECT_SERVER_NAME",
		"Мир",
		"World",
		"SERVER_SELECT_SERVER_FULL",
		"(заполнен)",
		"(full)",
		"MAIN_MENU_BACK",
		"НАЗАД",
		"BACK",
		"MAIN_MENU_PLAY",
		"ИГРАТЬ",
		"PLAY",
		"Shop",
		"МАГАЗИН",
		"SHOP",
		"MAIN_MENU_COMMUNITY",
		"КОМЬЮНИТИ",
		"COMMUNITY",
		"MAIN_MENU_PROFILE",
		"ПРОФИЛЬ",
		"PROFILE",
		"MAIN_MENU_TOP_MAPS",
		"ТОП КАРТ",
		"TOP MAPS",
		"MAIN_MENU_SETTINGS",
		"НАСТРОЙКИ",
		"SETTINGS",
		"MAIN_MENU_RATINGS",
		"РЕЙТИНГ",
		"RATING",
		"MAIN_MENU_BANK",
		"КУПИТЬ",
		"BUY",
		"MAIN_MENU_ACHIEVEMENTS",
		"ДОСТИЖЕНИЯ",
		"ACHIEVEMENTS",
		"START_MENU",
		"МЕНЮ",
		"MENU",
		"START_BUILDING",
		"СТРОИТЕЛЬСТВО",
		"BUILDING",
		"START_TEAM_BATTLE",
		"КОМАНДНЫЙ БОЙ",
		"TEAM BATTLE",
		"START_DEATHMATCH",
		"САМ ЗА СЕБЯ",
		"DEATHMATCH",
		"START_CTF",
		"ЗАХВАТ ФЛАГА",
		"CAPTURE THE FLAG",
		"START_LOOK",
		"ПОСМОТРЕТЬ",
		"LOOK",
		"START_PLAY",
		"ИГРАТЬ",
		"PLAY",
		"START_NEXT",
		"ДАЛЕЕ",
		"NEXT",
		"START_GAME_TYPE",
		"ВЫБОР ТИПА ИГРЫ",
		"SELECT GAME TYPE",
		"START_SELECT_MAP",
		"ВЫБОР КАРТЫ",
		"SELECT MAP",
		"START_DESCRIPTION_TITLE",
		"Описание:",
		"Description:",
		"START_DESCRIPTION_RANDOM",
		"Стройте на своей карте что-нибудь потрясающее и показывайте другим игрокам",
		"Build on your map something amazing and show the other players",
		"START_DESCRIPTION_BUILDING",
		"Вы попадете на карту к игроку, который занят строительством, помогите ему в этом!",
		"You will get the map to a player who is busy building, help him with that!",
		"START_DESCRIPTION_TEAM_BATTLE",
		"Две команды игроков пытаются выяснить - кто из них сильнее!",
		"Two teams of players trying to find out who is stronger!",
		"START_DESCRIPTION_DEATHMATCH",
		"Каждый сам за себя, доверять никому не стоит!",
		"Every man for himself, do not trust anyone!",
		"START_DESCRIPTION_CTF",
		"Захватите флаг чужой команды, чтобы победить!",
		"Grab the flag of another's team to win!",
		"START_DESCRIPTION_SURVIVAL",
		"Выживание Выживание Выживание Выживание Выживание",
		"Survival Survival Survival Survival Survival",
		"START_DESCRIPTION_ZOMBIE_VIRUS",
		"Зомби вирус проник в страну копателей, сможете ли вы выжить?",
		"Zombie virus entered the country Diggers, can you survive?",
		"START_DESCRIPTION_HUNGER_GAMES",
		"Станьте единственным выжившим в Голодных играх!",
		"Become the sole survivor in the Hunger Games!",
		"START_DESCRIPTION_ARCADE",
		"Беги, пока не останется один выживший",
		"Run for one life stand",
		"START_DESCRIPTION_HIDE_SEEK",
		"Игра в Прятки",
		"Hide Seek Game",
		"BANK_TITLE",
		"БАНК",
		"BANK",
		"BANK_ACTION_EXPIRED",
		"АКЦИЯ ИСТЕКАЕТ ЧЕРЕЗ",
		"ACTION EXPIRED AFTER",
		"BANK_BUY_GEMS",
		"КУПИТЬ КРИСТАЛЛЫ",
		"BUY GEMS",
		"BANK_BUY_GOLD",
		"КУПИТЬ МОНЕТЫ",
		"BUY GOLD",
		"BANK_ACTION",
		"АКЦИЯ X2!!!",
		"BONUS X2",
		"BANK_BUY",
		"КУПИТЬ",
		"BUY",
		"BANK_BUY_FOR",
		"за ",
		"for ",
		"MY_MAPS_BUY_SLOT",
		"Новый слот",
		"NEW SLOT",
		"MY_MAPS_TITLE1",
		"МОИ КАРТЫ",
		"MAPS",
		"MY_MAPS_TITLE2",
		"ОПИСАНИЕ",
		"DESCRIPTION",
		"MY_MAPS_LOAD",
		"ЗАГРУЗИТЬ",
		"LOAD",
		"MY_MAPS_GENERATE",
		"ПЕРЕГЕНЕРИРОВАТЬ",
		"GENERATE",
		"MY_MAPS_PUBLIC",
		"ОПУБЛИКОВАТЬ В ТОП",
		"PUBLIC IN TOP",
		"MY_MAPS_LOOK_IN_PUBLIC",
		"ПРОСМОТРЕТЬ В ТОПЕ",
		"LOOK IN TOP",
		"MY_MAPS_REMOVE_FROM_PUBLIC",
		"УБРАТЬ ИЗ ТОПА",
		"REMOVE FROM TOP",
		"MY_MAPS_SAVE",
		"СОХРАНИТЬ",
		"SAVE",
		"MY_MAPS_EMPTY",
		"Пустой слот",
		"Empty slot",
		"MY_MAPS_REWRITE",
		"Тут есть карта",
		"There's a map",
		"MY_MAPS_LOADING_SCREEN",
		"ЗАГРУЗКА\nИЗОБРАЖЕНИЯ",
		"LOADING\nSCREEN",
		"MY_MAPS_MAP_NAME",
		"Название\nкарты:",
		"Map\nname:",
		"MY_MAPS_MAP_PASSWORD",
		"Пароль\n(если надо):",
		"Password\n(if needed):",
		"MY_MAPS_MAP_DESCRIPTION",
		"Описание:",
		"Description:",
		"MY_MAPS_MAP_SIZE",
		"Размер карты:",
		"Map size:",
		"MY_MAPS_MAP_TYPE",
		"Тип карты:",
		"Map type:",
		"MY_MAPS_MAP_GAME_TYPE",
		"Тип игры:",
		"Game type:",
		"MY_MAPS_MAP_TIME",
		"Время:",
		"Time:",
		"MY_MAPS_MAP_DESTROYABLE",
		"Разрушаемый ландшафт",
		"Destroyable landscape",
		"MY_MAPS_MAP_BONUSES",
		"Падающие бонусы",
		"Falling bonuses",
		"MY_MAPS_MAP_CREATE",
		"СОЗДАТЬ",
		"CREATE",
		"MY_MAPS_MAP_PUBLIC",
		"ОПУБЛИКОВАТЬ",
		"PUBLIC",
		"MY_MAPS_MAP_LOAD",
		"ЗАГРУЗИТЬ",
		"LOAD",
		"MY_MAPS_MAP",
		"Карта",
		"Map",
		"SERVERS_TITLE2",
		"ОПИСАНИЕ",
		"DESCRIPTION",
		"SERVERS_ENTER",
		"ЗАЙТИ В ИГРУ",
		"ENTER TO GAME",
		"SERVERS_INFO",
		"ИНФОРМАЦИЯ",
		"INFORMATION",
		"SERVERS_NAME",
		"Название:",
		"Name:",
		"SERVERS_PLAYERS",
		"Игроков:",
		"Players:",
		"SERVERS_PASSWORD",
		"ПАРОЛЬ",
		"PASSWORD",
		"SERVERS_ENTER_PASSWORD",
		"Введите пароль",
		"Enter password",
		"SERVERS_WRONG_PASSWORD",
		"Неверный пароль",
		"Wrong password",
		"SETTINGS_TITLE1",
		"НАСТРОЙКИ",
		"SETTINGS",
		"SETTINGS_MOUSE_SENSIVITY",
		"ЧУВСТВИТЕЛЬНОСТЬ МЫШИ",
		"MOUSE SENSIVITY",
		"SETTINGS_SOUND_VOLUME",
		"ГРОМКОСТЬ ЗВУКОВ",
		"SOUND VOLUME",
		"SETTINGS_AMBIENT_VOLUME",
		"ГРОМКОСТЬ ПРИРОДЫ",
		"AMBIENT VOLUME",
		"SETTINGS_DESTRUCTION",
		"РАЗРУШЕНИЯ",
		"DESTRUCTION",
		"SETTINGS_SHOW_BUBBLES",
		"ФРАЗЫ НАД ИГРОКАМИ",
		"SHOW PHRASES OVER PLAYERS",
		"SETTINGS_FSMODE",
		"НА ВЕСЬ ЭКРАН",
		"FULL SCREEN",
		"RATINGS_TITLE",
		"РЕЙТИНГ",
		"RATING",
		"RATINGS_CATEGORIES",
		"Категории",
		"Category",
		"RATINGS_CATEGORY_0",
		"Война",
		"War",
		"RATINGS_CATEGORY_1",
		"Строительство",
		"Building",
		"RATINGS_CATEGORY_2",
		"Голодные игры",
		"The Hunger Games",
		"RATINGS_CATEGORY_3",
		"Беги",
		"Run",
		"RATINGS_NO_RATINGS",
		"Нет рейтинга",
		"No rating",
		"SHOP_TITLE1",
		"МАГАЗИН",
		"SHOP",
		"SHOP_TITLE2",
		"ОПИСАНИЕ",
		"DESCRIPTION",
		"SHOP_BUY_DAY",
		"на день",
		"one day",
		"SHOP_BUY_WEEK",
		"на неделю",
		"one week",
		"SHOP_BUY_FOREVER",
		"навсегда",
		"forever",
		"SHOP_BUY_MONTH",
		"на месяц",
		"one month",
		"SHOP_BUY_ONE",
		"КУПИТЬ",
		"BUY",
		"SHOP_BUY_PRICE",
		"Цена:",
		"Price:",
		"SHOP_BUY_EQUIP",
		"Надеть",
		"Put on",
		"SHOP_BUY_LOCK",
		"РАЗБЛОКИРОВАТЬ",
		"UNLOCK",
		"SHOP_BUY_USE",
		"ИСПОЛЬЗОВАТЬ",
		"USE",
		"SHOP_FOREVER_BUY",
		"Куплено навсегда",
		"Buy forever",
		"SHOP_ACTIVE_UNTIL",
		"Действует до:\n",
		"Active until:\n",
		"SHOP_YOU_HAVE",
		"У вас:",
		"You have:",
		"SHOP_EQUIPPED",
		"Надето",
		"Equipped",
		"SHOP_BOUGHT",
		"Куплено",
		"Bought",
		"SHOP_LOCKED",
		"Что бы купить это, вы должны сначала купить",
		"To buy this you must buy first",
		"SHOP_BUY_IN_PROGRESS",
		"Происходит покупка",
		"Buying in progress",
		"TOP_MAPS_TITLE1",
		"ТОП КАРТ",
		"MAPS",
		"TOP_MAPS_TITLE2",
		"ОПИСАНИЕ",
		"DESCRIPTION",
		"TOP_MAPS_NEW",
		"Новые карты",
		"New maps",
		"TOP_MAPS_ALL",
		"Лучшие карты",
		"Top maps",
		"TOP_MAPS_DAY",
		"Лучшие за день",
		"Top of the day",
		"TOP_MAPS_WEEK",
		"Лучшие за неделю",
		"Top of the week",
		"TOP_MAPS_MONTH",
		"Лучшие за месяц",
		"Top of the month",
		"TOP_MAPS_MAP_DESCRIPTION",
		"Описание:",
		"Description:",
		"TOP_MAPS_MAP_NAME",
		"Название\nкарты:",
		"Map\nname:",
		"TOP_MAPS_LOOK",
		"ПОСМОТРЕТЬ",
		"LOOK",
		"TOP_MAPS_COPY_URL",
		"ВЗЯТЬ АДРЕС КАРТЫ",
		"GET URL OF MAP",
		"TOP_MAPS_COPY_URL_DONE",
		"Адрес скопирован в буфер обмена",
		"URL copied to clipboard",
		"TOP_MAPS_COPY_URL_UNSUPPORTED",
		"Текущая платформа не поддерживает ссылки на карты",
		"Current platform does not support links to maps",
		"TOP_MAPS_LOADING_SCREEN",
		"ЗАГРУЗКА\nИЗОБРАЖЕНИЯ",
		"LOADING\nSCREEN",
		"TOP_MAPS_VOTE_YES",
		"ГОЛОС ЗА",
		"VOTE YES",
		"TOP_MAPS_AUTHOR",
		"Автор карты:",
		"Map author:",
		"TOP_MAPS_MORE_MAPS",
		"Еще карты",
		"More maps",
		"NOT_ENOUGH_MONEY_TITLE1",
		"ВНИМАНИЕ!",
		"ATTENTION!",
		"NOT_ENOUGH_MONEY_TITLE2",
		"НЕДОСТАТОЧНО СРЕДСТВ",
		"INSUFFICIENT FUNDS",
		"NOT_ENOUGH_MONEY_TITLE3",
		"ВАМ НЕ ХВАТАЕТ:",
		"YOU LACK THE:",
		"NOT_ENOUGH_MONEY_BUY",
		"КУПИТЬ",
		"BUY",
		"BONUS_TITLE1",
		"Бонус",
		"Bonus",
		"BONUS_TITLE2",
		"ВЫ ПОЛУЧИЛИ ЕЖЕДНЕВНЫЙ БОНУС",
		"YOU GOT THE DAILY BONUS",
		"BONUS_DAYS",
		"дней",
		"days",
		"BONUS_GEMS_TITLE1",
		"АКЦИЯ Х2!",
		"SALE",
		"BONUS_GEMS_TITLE2",
		"КРИСТАЛЛЫ УДВАИВАЮТСЯ ПРИ ПОКУПКЕ!",
		"CRYSTALS ARE DOUBLED WHEN PURCHASED!",
		"CHANGE_NAME_TITLE1",
		"НИК",
		"NAME",
		"CHANGE_NAME_TITLE2",
		"ВВЕДИТЕ НОВЫЙ НИКНЕЙМ",
		"TYPE YOUR NEW NAME",
		"CHANGE_NAME_BUSY",
		"НИК ЗАНЯТ, ПОПРОБУЙТЕ ДРУГОЙ",
		"NAME BUSY, TRY ANOTHER",
		"CHANGE_NAME_OK",
		"ПРОДОЛЖИТЬ",
		"CONTINUE",
		"INPUT_TEXT_OK",
		"ПРОДОЛЖИТЬ",
		"CONTINUE",
		"INPUT_TEXT_PICTURE_URL1",
		"КАРТИНКА",
		"PICTURE",
		"INPUT_TEXT_PICTURE_URL2",
		"Введите адрес (URL) картинки",
		"Enter the address (URL) of picture",
		"DEATHMATCH_TITLE",
		"ВОЙНА",
		"WAR",
		"DEATHMATCH_NAME",
		"ИМЯ",
		"NAME",
		"DEATHMATCH_SCORE",
		"СЧЁТ",
		"SCORE",
		"DEATHMATCH_VOICE_CHAT",
		"ИСПОЛЬЗОВАТЬ ГОЛОСОВОЙ ЧАТ",
		"USE VOICE CHAT",
		"DEATHMATCH_PLAY",
		"ИГРАТЬ",
		"PLAY",
		"DEATHMATCH_OBSERVE",
		"НАБЛЮДАТЬ",
		"OBSERVE",
		"EMOTIONS_TITLE",
		"СТИКЕРЫ",
		"EMOTIONS",
		"EMOTIONS_MORE",
		"ЕЩЁ СТИКЕРЫ...",
		"MORE EMOTIONS...",
		"GAME_MENU_TITLE",
		"МЕНЮ",
		"MENU",
		"GAME_MENU_RESUME",
		"ПРОДОЛЖИТЬ",
		"RESUME",
		"GAME_MENU_SELECT_WEAPON",
		"ВЫБРАТЬ ОРУЖИЕ",
		"SELECT WEAPON",
		"GAME_MENU_RESPAWN",
		"ВОЗРОДИТЬСЯ",
		"RESPAWN",
		"GAME_MENU_EMOTIONS",
		"СТИКЕРЫ",
		"EMOTIONS",
		"GAME_MENU_INVENTORY",
		"ИНВЕНТАРЬ",
		"INVENTORY",
		"GAME_MENU_SAVE",
		"СОХРАНИТЬ",
		"SAVE",
		"GAME_MENU_ESTIMATE",
		"ОЦЕНИТЬ",
		"ESTIMATE",
		"GAME_MENU_GET_GAME_URL",
		"ССЫЛКА НА ТЕКУЩУЮ ИГРУ",
		"URL TO CURRENT GAME",
		"GAME_MENU_HELP",
		"ПОМОЩЬ",
		"HELP",
		"GAME_MENU_EXIT",
		"ВЫЙТИ...",
		"EXIT",
		"GAME_MENU_EXIT_QUESTION",
		"ХОТИТЕ ВЫЙТИ?",
		"QUIT?",
		"GAME_MENU_INVENTORY_SYSTEM",
		"ОТКРЫТЬ ИНВЕНТАРЬ",
		"OPEN INVENTORY",
		"HUD_WATCH_MODE_TIP",
		"[Режим просмотра : TAB - информация о карте]",
		"[Watch mode : TAB - information about map]",
		"HUD_RESPAWN_TIP",
		"Нажмите ЛЕВУЮ КНОПКУ МЫШИ для возрождения",
		"Press LEFT MOUSE BUTTON to respawn",
		"HUD_FLAG_CAPTURED_TIP",
		"Вы несете флаг!",
		"You carry the flag!",
		"HUD_FEW_PLAYERS_TIP",
		"Недостаточно игроков",
		"Not enough players",
		"HUD_UNTIL_INFECTION_TIP",
		"До заражения...",
		"Until infection...",
		"HUD_YOU_ARE_ZOMBIE_TIP",
		"Вы стали зомби",
		"You become a zombie",
		"HUD_GAME_ENDED",
		"Игра закончена",
		"Game ended",
		"HUD_FLY_TIP1",
		"Пробел - взлет",
		"Space - takeoff",
		"HUD_FLY_TIP2",
		"Левый Шифт - приземление",
		"Left Shift - landing",
		"HUD_BATTLE_MORE_PLAYERS_TIP",
		"Необходимо 4 человека для зачисления опыта",
		"Need 4 players for gain experience",
		"HUD_CROSSHAIR_TAKE",
		"взять",
		"take",
		"HUD_CROSSHAIR_SIT",
		"войти/выйти",
		"enter/leave",
		"HUD_CROSSHAIR_OPEN",
		"открыть/закрыть",
		"open/close",
		"HUD_CROSSHAIR_ACTIVATE",
		"активировать",
		"activate",
		"HUD_CROSSHAIR_WRITE",
		"написать",
		"write",
		"HUD_CROSSHAIR_DRAW",
		"действие",
		"act",
		"HUD_CROSSHAIR_WHEEL",
		"вращать",
		"rotate",
		"HUD_CROSSHAIR_PUT",
		"установить",
		"place",
		"HUD_GOLD_CUP_HIDE",
		"Вы спрятали кубки на карте",
		"You hide cups on the map",
		"HUD_GOLD_CUP_ALL1",
		"Всего ",
		"Total ",
		"HUD_GOLD_CUP_ALL2",
		" кубков",
		" cups",
		"HUD_GOLD_CUP_AVAILABLE",
		"На карте есть золотые кубки",
		"The map has gold cups",
		"HUD_GOLD_CUP_FIND1",
		"Найдено ",
		"Found ",
		"HUD_GOLD_CUP_FIND2",
		" из ",
		" from ",
		"INVENTORY_TITLE",
		"ИНВЕНТАРЬ",
		"INVENTORY",
		"INVENTORY_BACK",
		"НАЗАД",
		"BACK",
		"INVENTORY_SHOP",
		"МАГАЗИН",
		"SHOP",
		"SELECT_WEAPON_TITLE",
		"ВЫБОР ОРУЖИЯ",
		"SELECT WEAPON",
		"SELECT_WEAPON_FIGHT",
		"В БОЙ!",
		"FIGHT!",
		"SELECT_WEAPON_BUY_TITLE",
		"КУПИТЬ ОРУЖИЕ МОЖНО В МАГАЗИНЕ",
		"YOU CAN BUY NEW WEAPON IN SHOP",
		"SELECT_WEAPON_BUY",
		"КУПИТЬ",
		"BUY",
		"SELECT_WEAPON_SELECT",
		"ВЫБЕРИТЕ ОРУЖИЕ",
		"SELECT WEAPON",
		"TEAM_BATTLE_TITLE",
		"ВЫБЕРИТЕ КОМАНДУ",
		"SELECT TEAM",
		"TEAM_BATTLE_BACK",
		"НАЗАД",
		"BACK",
		"TEAM_BATTLE_FOR_RED",
		"ЗА КРАСНЫХ",
		"FOR RED",
		"TEAM_BATTLE_FOR_BLUE",
		"ЗА СИНИХ",
		"FOR BLUE",
		"TEAM_BATTLE_FOR_ZOMBIES",
		"ЗА ЗОМБИ",
		"FOR ZOMBIES",
		"TEAM_BATTLE_FOR_SURVIVORS",
		"ЗА ВЫЖИВШИХ",
		"FOR SURVIVORS",
		"TEAM_BATTLE_OBSERVE",
		"НАБЛЮДАТЬ",
		"OBSERVE",
		"TEAM_BATTLE_RED",
		"Террористы",
		"RED",
		"TEAM_BATTLE_BLUE",
		"Спецназ",
		"BLUE",
		"TEAM_BATTLE_ZOMBIES",
		"ЗОМБИ",
		"ZOMBIES",
		"TEAM_BATTLE_SURVIVORS",
		"ВЫЖИВШИЕ",
		"SURVIVORS",
		"TEAM_BATTLE_NAME",
		"ИМЯ",
		"NAME",
		"TEAM_BATTLE_SCORE",
		"СЧЁТ",
		"SCORE",
		"TEAM_BATTLE_DRAW",
		"Ничья",
		"Draw",
		"TEAM_BATTLE_RED_WIN",
		"Победа красных!",
		"Red team win!",
		"TEAM_BATTLE_BLUE_WIN",
		"Победа синих!",
		"Blue team win!",
		"DEATHMATCH_WIN",
		"Победил ",
		"Winner is ",
		"TAB_MENU_SERVER",
		"СЕРВЕР:",
		"SERVER:",
		"TAB_MENU_ADMINISTRATION",
		"АДМИНИСТРИРОВАНИЕ",
		"ADMINISTRATION",
		"TAB_MENU_NEW_PLAYERS_BUILDING",
		"НОВЫЕ ИГРОКИ НЕ МОГУТ ИЗМЕНЯТЬ КАРТУ",
		"NEW PLAYERS CAN NOT CHANGE THE MAP",
		"TAB_MENU_BAN",
		"ЗАБАНИТЬ",
		"BAN",
		"TAB_MENU_UNBAN",
		"РАЗБАНИТЬ",
		"UNBAN",
		"TAB_MENU_PLAYERS",
		"ИГРОКИ:",
		"PLAYERS:",
		"TAB_MENU_YOU",
		"Это вы",
		"It's you",
		"STORE_BLOCKS",
		"БЛОКИ",
		"BLOCKS",
		"STORE_BLOCKS_WOOD",
		"ДЕРЕВЯННЫЕ",
		"WOOD",
		"STORE_BLOCKS_STONE",
		"КАМЕННЫЕ",
		"STONE",
		"STORE_BLOCKS_NATURE",
		"ПРИРОДНЫЕ",
		"NATURE",
		"STORE_BLOCKS_COLORED",
		"ЦВЕТНЫЕ",
		"COLORED",
		"STORE_BLOCKS_GLASS",
		"СТЕКЛЯННЫЕ",
		"GLASS",
		"STORE_BLOCKS_CELL",
		"РЕШЕТЧАТЫЕ",
		"CELL",
		"STORE_PETS",
		"ЖИВОТНЫЕ",
		"PETS",
		"STORE_MAPS",
		"КАРТЫ",
		"MAPS",
		"STORE_SKINS",
		"ОДЕЖДА",
		"SKINS",
		"STORE_PLANTS",
		"РАСТЕНИЯ",
		"PLANTS",
		"STORE_WEAPONS",
		"ОРУЖИЕ",
		"WEAPONS",
		"STORE_DECORATIONS",
		"СРЕДНЕВЕКОВЫЕ ДЕКОРАЦИИ",
		"DECORATIONS OLD",
		"STORE_TOOLS",
		"ИНСТРУМЕНТЫ",
		"TOOLS",
		"STORE_BONUSES",
		"БОНУСЫ",
		"BONUSES",
		"STORE_DECORATIONS_NEW",
		"СОВРЕМЕННЫЕ ДЕКОРАЦИИ",
		"DECORATIONS MODERN",
		"STORE_DECORATIONS_STAR",
		"Сеты декораций",
		"Decorations sets",
		"GAME_TYPE_RANDOM",
		"Ваша карта",
		"Your world",
		"GAME_TYPE_BUILDING",
		"Строительство",
		"Building",
		"GAME_TYPE_TEAM_BATTLE",
		"Командный бой",
		"Team battle",
		"GAME_TYPE_DEATHMATCH",
		"Война",
		"War",
		"GAME_TYPE_CTF",
		"Захват флага",
		"Capture the flag",
		"GAME_TYPE_SURVIVAL",
		"Выживание",
		"Survival",
		"GAME_TYPE_ZOMBIE_VIRUS",
		"Зомби вирус",
		"Zombie virus",
		"GAME_TYPE_HUNGER_GAMES",
		"Голодные игры",
		"HungerGames",
		"GAME_TYPE_ARCADE",
		"Беги!",
		"Run Run",
		"GAME_TYPE_HIDE_SEEK",
		"Прятки",
		"Hide Seek",
		"MAP_SIZE_LARGE",
		"Большая",
		"Large",
		"MAP_SIZE_HUGE",
		"Огромная",
		"Huge",
		"MAP_TYPE_STANDART",
		"Стандартная",
		"Standart",
		"MAP_TYPE_FLAT",
		"Плоская",
		"Flat",
		"MAP_TYPE_SAND",
		"Пустыня",
		"Sand",
		"MAP_TYPE_OCEAN",
		"Океан",
		"Ocean",
		"MAP_TYPE_ISLAND",
		"Острова",
		"Islands",
		"MAP_TYPE_SNOWLAND",
		"Зима",
		"Snowland",
		"MAP_TIME_DAY",
		"День",
		"Day",
		"MAP_TIME_NIGHT",
		"Ночь",
		"Night",
		"MAP_TIME_SWITCH",
		"День/Ночь",
		"Day/Night",
		"DECOR_DARK_CASTLE",
		"Темный замок",
		"Dark Castle",
		"HG_ARCHER_BUILD",
		"Лучник",
		"Archer",
		"HG_KNIGHT_BUILD",
		"Рыцарь",
		"Knight",
		"WEAPON_PISTOLS",
		"Пистолеты",
		"Pistols",
		"WEAPON_SHOTGUNS",
		"Дробовики",
		"Shotguns",
		"WEAPON_SNIPER_RIFLES",
		"Ружья",
		"Sniper Rifles",
		"WEAPON_GRENADE_LAUNCHERS",
		"Гранатометы",
		"Grenade Launchers",
		"WEAPON_RIFLES",
		"Автоматы",
		"Rifles",
		"WEAPON_STAT_DAMAGE",
		"Урон",
		"Damage",
		"WEAPON_STAT_RATE",
		"Скорострельность",
		"Fire Rate",
		"WEAPON_STAT_ACCURACY",
		"Точность",
		"Accuracy",
		"WEAPON_STAT_VOLUME",
		"Патроны",
		"Volume",
		"WEAPON_TODAY",
		"Современное оружие",
		"Modern Weapons",
		"WEAPON_WW2",
		"Оружие Второй мировой войны",
		"World War II weapons",
		"DECOR_PAINTINGS",
		"Картины",
		"Paintings",
		"DESTRUCTION_SIMPLE",
		"Простые",
		"Simple",
		"DESTRUCTION_MEDIUM",
		"Средние",
		"Medium",
		"DESTRUCTION_EPIC",
		"Эпичные",
		"Epic",
		"SKIN_BASE",
		"Базовый",
		"Base",
		"SKIN_PRO",
		"Профессии",
		"Professions",
		"SKIN_MIDDLE_AGES",
		"Средневековье",
		"Middle Ages",
		"BLOCK_FORMS",
		"Формы блоков",
		"Block forms",
		"BLOCK_TYPES",
		"Типы блоков",
		"Block types",
		"BLOCK_SETS",
		"СЕТЫ БЛОКОВ",
		"Block sets",
		"COLOR_BLOCK_SETS",
		"Цветные блоки",
		"Color Block",
		"SKIN_WORLD_WAR_II",
		"Вторая мировая",
		"World War II",
		"SKIN_MODERNITY",
		"Современность",
		"Modernity",
		"SKIN_SUPERHEROES",
		"Супер Копатели",
		"Super Diggers",
		"HINT_ALLOW_MICROPHONE",
		"Нажмите Allow в следующем окне для активации микрофона",
		"Click Allow in the next window to activate the microphone",
		"HINT_MISSED_SPAWN_POINTS",
		"Нет точек спавна для красной команды!\nРежим игры переключен в строительный.",
		"No spawn points for the red team!\nGame type switched to the building.",
		"HINT_MISSED_BLUE_SPAWN_POINTS",
		"Нет точек спавна для синей команды!\nРежим игры переключен в строительный.",
		"No spawn points for the blue team!\nGame type switched to the building.",
		"HINT_MISSED_RED_FLAG",
		"Нет красного флага!\nРежим игры переключен в строительный.",
		"Missed red flag!\nGame type switched to the building.",
		"HINT_MANY_RED_FLAGS",
		"Красный флаг должен быть только один!\nРежим игры переключен в строительный.",
		"Red flag must be only one!\nGame type switched to the building.",
		"HINT_MISSED_BLUE_FLAG",
		"Нет синего флага!\nРежим игры переключен в строительный.",
		"Missed blue flag!\nGame type switched to the building.",
		"HINT_MANY_BLUE_FLAGS",
		"Синий флаг должен быть только один!\nРежим игры переключен в строительный.",
		"Blue flag must be only one!\nGame type switched to the building.",
		"HINT_YOU_HAVE_BAN",
		"Вы получили бан на этом сервере",
		"You banned on this server",
		"HINT_SERVER_CLOSED",
		"Сервер на котором вы играли был закрыт администратором",
		"Server on which you played was closed by the administrator",
		"EXIT_TEXT",
		"Выход",
		"Exit",
		"EXIT_DESCRIPTION",
		"Вы можете оставить сервер включенным на время вашего отсутсвия. Зажав TAB в игре, вы можете назначить модератора, который будет следить за сервером пока вас нет",
		"You can leave the server on for the duration of your absence. Holding TAB in the game, you can assign a moderator who will monitor the server while you are gone",
		"EXIT_SERVER_OFF",
		"Cервер выключить",
		"Shut down server",
		"EXIT_STILL_SERVER",
		"Cервер пусть работает",
		"Still server alive",
		"EXIT_RESUME",
		"Вернуться в игру",
		"Back to game",
		"GAME_URL_FIND_ROOM",
		"Поиск игры",
		"Find game",
		"GAME_URL_GAME_NOT_FOUND",
		"Игра не найдена",
		"Game not found",
		"GAME_URL_URL_DONE",
		"Адрес скопирован в буфер обмена",
		"URL copied to clipboard",
		"GAME_URL_URL_UNSUPPORTED",
		"Текущая платформа не поддерживает ссылки на карты",
		"Current platform does not support links to maps",
		"BANNED_TITLE",
		"Бан",
		"Banned",
		"STORE_BLOCKS_TILE",
		"КРЫШИ",
		"Roofs",
		"STORE_BLOCKS_SETS",
		"СЕТЫ БЛОКОВ",
		"Blocks sets",
		"BANNED_UNBAN",
		"Разбанить",
		"Unban",
		"NAME_TOO_SHORT",
		"Никнейм слишком короткий",
		"Name too short",
		"NAME_TOO_LONG",
		"Никнейм слишком длинный",
		"Name too long",
		"CHECKPOINT",
		"Чекпоинт! Если вы умрете, то появитесь здесь",
		"Checkpoint! If you die, you will respwan here",
		"CANT_TAKE_ITEMS",
		", чужие вещи брать запрещено",
		", to take other people's things prohibited",
		"CANT_DESTROY_ITEMS",
		", чужие вещи разрушать запрещено",
		", to destroy other people's things prohibited",
		"CANT_TAKE_AND_DESTROY_ITEMS",
		", чужие вещи брать и разрушать запрещено",
		", to take other people's things and destroy prohibited",
		"CANT_EDIT_PICTURES",
		"Чужие картины изменять запрещено",
		"Foreign pictures must not be changed",
		"CANT_DESTROY_SPWAN",
		"Нельзя разрушать точки спавна",
		"You can not destroy the spawn points",
		"CANT_MOVE_SPWAN",
		"Во время командного боя точку возрождения передвигать нельзя",
		"During the battle you can not move the spawn point",
		"CANT_MOVE_SPWAN_ADMIN",
		"Точку возрождения может передвигать только администратор карты",
		"Spawn point can move only map administrator",
		"CANT_EDIT_PLATE",
		"Текст чужих табличек изменять запрещено",
		"Text foreign plates must not be changed",
		"CANT_EDIT_MAP",
		"Изменять карту нельзя, обратитесь к администратору карты, чтобы получить возможность строить",
		"Map can not change, contact the administrator of the map to get the opportunity to build",
		"CANT_EDIT_MAP_IN_WATCH",
		"В режиме просмотра изменять карту нельзя",
		"In Watch mode, you can not change the map",
		"CANT_DESTROY_IN_WATCH",
		"В режиме просмотра разрушение запрещено",
		"In Watch mode, the destruction of prohibited",
		"CANT_BUILD_GAME_TYPE",
		"В данном режиме строительство запрещено",
		"In this game mode construction is prohibited",
		"CANT_BUILD_ZT_END",
		"У вас закончились блоки для строительства",
		"End block",
		"CANT_SET_NY16_ITEM",
		"Данную декорацию нельзя установить на чужой карте",
		"This scenery can not be installed on someone else's map",
		"CUP_PLAYER",
		"Игрок ",
		"Player ",
		"CUP_PLAYER_FIND",
		" нашел кубок!",
		" found cup!",
		"CUP_PLAYER_FIND_ALL",
		" нашел все кубки!!!",
		" found all cups!!!",
		"FOUND_5_GOLD",
		" нашел 5 золота",
		" found 5 gold coins",
		"BUILD_PLAYER",
		"Игроку ",
		"Player ",
		"PLAYER_CANT_BAN",
		" заблокировать нельзя, данный игрок является разработчиком",
		" can not ban. This player admin",
		"PLAYER_BANNED",
		" был забанен модератором",
		" was banned by the moderator",
		"PLAYER_UNBANNED",
		" разбанен модератором",
		" unbaned by the moderator",
		"PLAYER_BANNED_ENTER",
		" хочет войти в игру, но он забанен",
		" wants to get into the game, but he is banned",
		"LOCK_FIND_KEY",
		" нашел ",
		" found ",
		"LOCK_REMANING_KEYS",
		"Чтобы открыть дверь нужно найти ",
		"To open the door you need to find ",
		"ITEMS_PACK_TITLE",
		"СОСТАВ ПАКА",
		"PACK CONTENT",
		"STORE_BLOCK_TILE",
		"Крыши",
		"Roof",
		"MILITARY_CUBES",
		"Военные",
		"Military",
		"INDUSTRIAL_CUBES",
		"Промышленные",
		"Industrial",
		"STORE_BLOCK_SETS",
		"СЕТЫ БЛОКОВ",
		"Block Sets",
		"WEAPON_OTHER",
		"Бонусы",
		"Bonus",
		"BATTLE_RESULT_TITLE",
		"Итоги боя",
		"Battle Result",
		"PURCHASE_BATTLE_GREANDES",
		"Гранаты",
		"Grenades",
		"PURCHASE_BATTLE_HEALTH",
		"Аптечка",
		"Health",
		"PURCHASE_BATTLE_SHIELD",
		"Броня",
		"Shield",
		"PURCHASE_MORE_EXPERIENCE",
		"Премиум",
		"Premium",
		"PURCHASE_BLOCK_KIND_CORNER",
		"Угол",
		"Corner",
		"PURCHASE_BLOCK_KIND_FENCE",
		"Столбик",
		"Сolumn",
		"PURCHASE_BLOCK_KIND_HALF",
		"Пол блока",
		"Half",
		"PURCHASE_BLOCK_KIND_DIAGONAL",
		"Диагональный блок",
		"Diagonal",
		"PURCHASE_BLOCK_KIND_STAIR",
		"Лестница",
		"Stair",
		"PURCHASE_STONE_BLOCKS",
		"Каменные кубы",
		"Stone blocks",
		"PURCHASE_COLORED_BLOCKS",
		"Цветные кубы",
		"Colored blocks",
		"PURCHASE_WOODEN_BLOCKS",
		"Деревянные кубы",
		"Wooden blocks",
		"PURCHASE_GRATES_BLOCKS",
		"Решетки",
		"Grates",
		"PURCHASE_GLASS_BLOCKS",
		"Стекла",
		"Glass",
		"PURCHASE_WATER_BLOCK",
		"Вода",
		"Water",
		"PURCHASE_LAVA_BLOCK",
		"Лава",
		"Lava",
		"PURCHASE_TRAMPOLINE_BLOCK",
		"Блок-батут",
		"Block trampoline",
		"PURCHASE_TEAM_BLOCKS",
		"Командные кубы",
		"Team blocks",
		"PURCHASE_ICE_BLOCK",
		"Лед",
		"Ice",
		"PURCHASE_WOODEN_CHAIR",
		"Деревянный стул",
		"Wooden chair",
		"PURCHASE_WOODEN_TABLE",
		"Деревянный стол",
		"Wooden table",
		"PURCHASE_BUCKET",
		"Ведро",
		"Bucket",
		"PURCHASE_BASKET",
		"Корзина",
		"Basket",
		"PURCHASE_BARREL",
		"Бочка",
		"Barrel",
		"PURCHASE_FENCE",
		"Забор",
		"Fence",
		"PURCHASE_CHEST",
		"Сундук",
		"Chest",
		"PURCHASE_SIGNPOST",
		"Указатель",
		"Signpost",
		"PURCHASE_SIMPLE_BED",
		"Кровать",
		"Bed",
		"PURCHASE_NIGHTSTAND",
		"Тумбочка",
		"Nightstand",
		"PURCHASE_CUPBOARD",
		"Шкаф",
		"Cupboard",
		"PURCHASE_STAIRS",
		"Ступеньки",
		"Stairs",
		"PURCHASE_DOOR",
		"Дверь",
		"Door",
		"PURCHASE_PLATE",
		"Табличка",
		"Plate",
		"PURCHASE_FLOOR_PLATE",
		"Напольная табличка",
		"Floor plate",
		"PURCHASE_WALL_PLATE",
		"Настенная табличка",
		"Wall plate",
		"PURCHASE_FLOOR_TORCH",
		"Напольный факел",
		"Floor torch",
		"PURCHASE_TORCH",
		"Факел",
		"Torch",
		"PURCHASE_WALL_TORCH",
		"Настенный факел",
		"Wall torch",
		"PURCHASE_CHANGE_NICKNAME",
		"Сменить ник",
		"Change nickname",
		"PURCHASE_IMPROVED_PICK",
		"Улучшенная кирка",
		"Improved pick",
		"PURCHASE_DYNAMITE",
		"Динамит",
		"TNT",
		"PURCHASE_AIR_BOMB",
		"Авиа бомба",
		"Air bomb",
		"PURCHASE_NORMAL_SKIN",
		"Копатель",
		"Digger",
		"PURCHASE_LADDER",
		"Лестница",
		"Ladder",
		"PURCHASE_BOOK",
		"Книга",
		"Book",
		"PURCHASE_BIG_TABLE",
		"Большой стол",
		"Large table",
		"PURCHASE_STONE_BED",
		"Каменная кровать",
		"Stone bed",
		"PURCHASE_STONE_CHAIR",
		"Каменный стул",
		"Stone chair",
		"PURCHASE_STONE_CHEST",
		"Каменный сундук",
		"Stone chest",
		"PURCHASE_STONE_FENCE",
		"Каменный забор",
		"Stone fence",
		"PURCHASE_STONE_TABLE",
		"Каменный стол",
		"Stone table",
		"PURCHASE_TOMB",
		"Надгробие",
		"Tomb",
		"PURCHASE_WOODEN_BENCH",
		"Деревянная скамейка",
		"Wooden bench",
		"PURCHASE_STONE_BENCH",
		"Каменная скамейка",
		"Stone bench",
		"PURCHASE_STONE_TORCH",
		"Каменный факел",
		"Stone torch",
		"PURCHASE_STONE_WALL_TORCH",
		"Каменный настенный факел",
		"Stone wall torch",
		"PURCHASE_STONE_FLOOR_TORCH",
		"Каменный напольный факел",
		"Stone floor torch",
		"PURCHASE_CAKE",
		"Торт",
		"Cake",
		"PURCHASE_WOODEN_PLATE",
		"Деревянная тарелка",
		"Wooden plate",
		"PURCHASE_SPOON",
		"Ложка",
		"Spoon",
		"PURCHASE_FORCK",
		"Вилка",
		"Fork",
		"PURCHASE_MUG",
		"Кружка",
		"Mug",
		"PURCHASE_JUG",
		"Кувшин",
		"Jug",
		"PURCHASE_METAL_PLATE",
		"Металлическая тарелка",
		"Metal plate",
		"PURCHASE_BREAD",
		"Хлеб",
		"Bread",
		"PURCHASE_CHEESE",
		"Сыр",
		"Cheese",
		"PURCHASE_CHIKEN",
		"Курица",
		"Chicken",
		"PURCHASE_PIG",
		"Свинина",
		"Pig",
		"PURCHASE_FISH_FOOD",
		"Рыба",
		"Fish",
		"PURCHASE_STEAK",
		"Стейк",
		"Steak",
		"PURCHASE_ORANGE",
		"Апельсин",
		"Orange",
		"PURCHASE_PIZZA",
		"Пицца",
		"Pizza",
		"PURCHASE_COLA",
		"Кола",
		"Cola",
		"PURCHASE_BURGER",
		"Бургер",
		"Burger",
		"PURCHASE_PIE",
		"Пирог",
		"Pie",
		"PURCHASE_DARK_CASTLE_BED",
		"Кровать",
		"Bed",
		"PURCHASE_DARK_CASTLE_BENCH",
		"Скамейка",
		"Bench",
		"PURCHASE_DARK_CASTLE_BOOK_CONSOLE",
		"Книга",
		"Book",
		"PURCHASE_DARK_CASTLE_BOX_BIG",
		"Большой шкаф",
		"Large closet",
		"PURCHASE_DARK_CASTLE_BOX_BIG_BOOKS",
		"Книжный шкаф",
		"Bookcase",
		"PURCHASE_DARK_CASTLE_BOX_SMALL",
		"Маленький шкаф",
		"Small wardrobe",
		"PURCHASE_DARK_CASTLE_CAGE",
		"Клетка",
		"Cell",
		"PURCHASE_DARK_CASTLE_CHAIN",
		"Цепь",
		"Сhain",
		"PURCHASE_DARK_CASTLE_CHAIN_01",
		"Цепь",
		"Сhain",
		"PURCHASE_DARK_CASTLE_CHAIN_02",
		"Цепь",
		"Сhain",
		"PURCHASE_DARK_CASTLE_CHAIN_03",
		"Цепь",
		"Сhain",
		"DARK_CASTLE_CUBES",
		"Темный замок",
		"Dark castle",
		"CITY_INTERIOR",
		"Квартира/Офис",
		"City interior",
		"CITY_EXTERIOR",
		"Современный город",
		"City exterior",
		"PURCHASE_DARK_CASTLE_CHAIR",
		"Стул",
		"Chair",
		"PURCHASE_DARK_CASTLE_CHEST",
		"Сундук",
		"Chest",
		"PURCHASE_DARK_CASTLE_COFFIN",
		"Гроб",
		"Coffin",
		"PURCHASE_DARK_CASTLE_COFFIN_01",
		"Гроб",
		"Coffin",
		"PURCHASE_DARK_CASTLE_COFFIN_02",
		"Гроб",
		"Coffin",
		"PURCHASE_DARK_CASTLE_DARK_PICTURE_01",
		"Картина",
		"Picture",
		"PURCHASE_DARK_CASTLE_DARK_PICTURE_02",
		"Картина",
		"Picture",
		"PURCHASE_DARK_CASTLE_DARK_PICTURE_03",
		"Картина",
		"Picture",
		"PURCHASE_DARK_CASTLE_DOOR",
		"Дверь",
		"Door",
		"PURCHASE_DARK_CASTLE_FENCE",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_FENCE_END",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_FENCE_I",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_FENCE_L",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_FENCE_T",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_FENCE_X",
		"Забор",
		"Fence",
		"PURCHASE_DARK_CASTLE_GARGOYLEY",
		"Статуя Гаргули",
		"Statue of Gargoyles",
		"PURCHASE_DARK_CASTLE_SARCOPHAGUS",
		"Саркофаг",
		"Sarcophagus",
		"PURCHASE_DARK_CASTLE_SKULL_MUG",
		"Чаша",
		"Cup",
		"PURCHASE_DARK_CASTLE_STANDARD",
		"Знамя",
		"Banner",
		"PURCHASE_DARK_CASTLE_STANDARD_01",
		"Знамя",
		"Banner",
		"PURCHASE_DARK_CASTLE_STANDARD_02",
		"Знамя",
		"Banner",
		"PURCHASE_DARK_CASTLE_TABLE_BIG",
		"Большой стол",
		"Large table",
		"PURCHASE_DARK_CASTLE_TABLE_SMALL",
		"Маленький стол",
		"Small table",
		"PURCHASE_DARK_CASTLE_THRONE",
		"Трон",
		"Throne",
		"PURCHASE_DARK_CASTLE_TORCH_01",
		"Факел",
		"Torch",
		"PURCHASE_DARK_CASTLE_TORCH_02",
		"Факел",
		"Torch",
		"PURCHASE_DARK_CASTLE_TROLL",
		"Статуя Троля",
		"Troll Statue",
		"PURCHASE_DARK_CASTLE_HERALDRY",
		"Геральдика",
		"Heraldry",
		"PURCHASE_FLOWERS1",
		"Цветы 1",
		"Flowers pack 1",
		"PURCHASE_FLOWERS2",
		"Цветы 2",
		"Flowers pack 2",
		"PURCHASE_FLOWERS3",
		"Цветы 3",
		"Flowers pack 3",
		"PURCHASE_BLUE_FLOWER",
		"Синий цветок",
		"Blue flower",
		"PURCHASE_RED_FLOWER",
		"Красный цветок",
		"Red flower",
		"PURCHASE_WHITE_FLOWER",
		"Белый цветок",
		"White Flower",
		"PURCHASE_YELLOW_FLOWER",
		"Желтый цветок",
		"Yellow Flower",
		"PURCHASE_PINK_FLOWER",
		"Розовый цветок",
		"Pink Flower",
		"PURCHASE_BLUEBERRIES",
		"Черника",
		"Blueberries",
		"PURCHASE_STRAWBERRIES",
		"Клубника",
		"Strawberries",
		"PURCHASE_CAMOMILE",
		"Ромашка",
		"Camomile",
		"PURCHASE_FERN",
		"Папоротник",
		"Fern",
		"PURCHASE_BELL_FLOWER",
		"Колокольчик",
		"Bell flower",
		"PURCHASE_GRASS",
		"Трава",
		"Grass",
		"PURCHASE_MUSHROOM",
		"Гриб",
		"Mushroom",
		"PURCHASE_WHEAT",
		"Пшеница",
		"Wheat",
		"PURCHASE_FISH",
		"Рыбка",
		"Fish",
		"PURCHASE_FISH1",
		"Рыба",
		"Fish",
		"PURCHASE_FISH2",
		"Рыба",
		"Fish",
		"PURCHASE_FISH3",
		"Рыба",
		"Fish",
		"PURCHASE_CAT",
		"Рыжая кошка",
		"Redhead сat",
		"PURCHASE_CAT_BLACK",
		"Черная кошка",
		"Black сat",
		"PURCHASE_CAT_STRIPED",
		"Серая кошка",
		"Striped сat",
		"PURCHASE_DOG",
		"Собака",
		"Dog",
		"PURCHASE_CRAB",
		"Краб",
		"Crab",
		"PURCHASE_BOAR",
		"Кабан",
		"Boar",
		"PURCHASE_FLAT_MAP",
		"Плоская",
		"Flat",
		"PURCHASE_DESERT",
		"Пустыня",
		"Desert",
		"PURCHASE_OCEAN",
		"Океан",
		"Ocean",
		"PURCHASE_ISLANDS",
		"Острова",
		"Islands",
		"PURCHASE_WINTER",
		"Зима",
		"Winter",
		"PURCHASE_GLOCK",
		"Глок 18",
		"Glock 18",
		"PURCHASE_MP5",
		"Пистолет-пулемет MP5",
		"MP5",
		"PURCHASE_AK47",
		"АК47",
		"AK47",
		"PURCHASE_M4A",
		"M4A",
		"M4A",
		"PURCHASE_RIFLE",
		"Ружье",
		"Rifle",
		"PURCHASE_SNIPER_RIFLE",
		"Снайперское ружье",
		"Sniper rifle",
		"PURCHASE_SHOTGUN",
		"SWAT Sgotgun",
		"SWAT Shotgun",
		"PURCHASE_GRENADE_GUN",
		"Гранатомет",
		"Grenade-gun",
		"PURCHASE_MP40",
		"МП40",
		"MP40",
		"PURCHASE_PPSH",
		"PPSH",
		"PPSH",
		"PURCHASE_THOMPSON",
		"THOMSON",
		"THOMPSON",
		"PURCHASE_PIRATE",
		"Пират",
		"Pirate",
		"PURCHASE_KNIGHT",
		"Рыцарь",
		"Knight",
		"PURCHASE_DARK_KO",
		"Темный Копатель",
		"Dark Digger",
		"PURCHASE_DARK_KO_SKIN",
		"Темный Копатель",
		"Dark Digger",
		"PURCHASE_GIRL_SKIN_1",
		"Девушка",
		"Girl",
		"PURCHASE_GIRL_SKIN_2",
		"Девушка",
		"Girl",
		"PURCHASE_IRON_KO",
		"Железный Копатель",
		"Iron Digger",
		"PURCHASE_IRON_KO_SKIN",
		"Железный Копатель",
		"Iron Digger",
		"PURCHASE_SKELETON",
		"Скелет Воин",
		"Skeleton Warrior",
		"PURCHASE_SKELETON_SKIN",
		"Скелет Воин",
		"Skeleton Warrior",
		"PURCHASE_KNIGHT0",
		"Новобранец Рыцарей",
		"Recruit Knight",
		"PURCHASE_EPIC_KNIGHT",
		"Эпичный рыцарь",
		"Epic knight",
		"PURCHASE_CAPTAIN_PIRATE",
		"Капитан Пиратов",
		"Captain Pirate",
		"PURCHASE_VIKING",
		"Викинг",
		"Viking",
		"PURCHASE_VIKING_SKIN_1",
		"Викинг",
		"Viking",
		"PURCHASE_ZOMBIE",
		"Зомби",
		"Zombie",
		"PURCHASE_DEATH_KNIGHT",
		"Рыцарь смерти",
		"Death knight",
		"PURCHASE_DEATH_KNIGHT_SKIN",
		"Рыцарь смерти",
		"Death knight",
		"PURCHASE_STALKER",
		"Сталкер",
		"Stalker",
		"PURCHASE_SOVIET_SOLDIER",
		"Советский солдат",
		"Soviet soldier",
		"PURCHASE_SWAT",
		"Спецназ",
		"Special Forces",
		"PURCHASE_US_SOLDIER",
		"Американский солдат",
		"U.S. soldier",
		"PURCHASE_GERMAN_OFICER",
		"Немецкий офицер",
		"German officer",
		"PURCHASE_RESPAWN",
		"Точка возрождения",
		"Respawn point",
		"PURCHASE_GOLD_CUP",
		"Золотой кубок",
		"Gold cup",
		"PURCHASE_BLOAT",
		"Лодка",
		"Boat",
		"PURCHASE_ADV_SMILES",
		"Расширенный пак стикеров",
		"Advanced pack of emotions",
		"PURCHASE_RAILS",
		"Рельсы",
		"Rails",
		"PURCHASE_TROLLEY",
		"Вагонетка",
		"Trolley",
		"PURCHASE_DAY_NIGHT",
		"День / Ночь",
		"Day / Night",
		"PURCHASE_MEM_FACES",
		"Мем фейсы",
		"Internet faces",
		"PURCHASE_TEAM_DOORS",
		"Командные двери",
		"Team doors",
		"PURCHASE_TEAM_RED_DOOR",
		"Командная дверь красных",
		"Team red door",
		"PURCHASE_TEAM_BLUE_DOOR",
		"Командная дверь синих",
		"Team blue door",
		"PURCHASE_TEAM_RESPAWN",
		"Точка возрождения команды",
		"Team respawn",
		"PURCHASE_RED_SPAWN",
		"Точка появления красных",
		"Red spawn",
		"PURCHASE_BLUE_SPAWN",
		"Точка появления синих",
		"Blue spawn",
		"PURCHASE_LIFE",
		"Жизни",
		"Life",
		"PURCHASE_ARMOR",
		"Броня",
		"Armor",
		"PURCHASE_GRENADES",
		"Гранаты",
		"Grenades",
		"PURCHASE_WEAPONS",
		"Патроны",
		"Ammunition",
		"PURCHASE_RESPAWN_POINT",
		"Точка появления",
		"Respawn point",
		"PURCHASE_FLAG",
		"Флаг",
		"Flag",
		"PURCHASE_PAINTING_01",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_02",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_03",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_04",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_05",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_06",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_07",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_08",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_09",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_10",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_12",
		"Картина",
		"Painting",
		"PURCHASE_PAINTING_13",
		"Картина",
		"Painting",
		"PURCHASE_LOCK_DOOR",
		"Запертая дверь",
		"Locked door",
		"PURCHASE_LOCK_DOOR_RED",
		"Красная запертая дверь",
		"Red locked door",
		"PURCHASE_LOCK_DOOR_YELLOW",
		"Желтая запертая дверь",
		"Yellow locked door",
		"PURCHASE_LOCK_DOOR_BLUE",
		"Синяя запертая дверь",
		"Blue locked door",
		"PURCHASE_LOCK_DOOR_GREEN",
		"Зеленая запертая дверь",
		"Green locked door",
		"PURCHASE_LOCK_DOOR_WHITE",
		"Белая запертая дверь",
		"White locked door",
		"PURCHASE_LOCK_KEY",
		"Ключ от запертой двери",
		"Key for locked door",
		"PURCHASE_LOCK_KEY_RED",
		"Красный ключ от запертой двери",
		"Red key for locked door",
		"PURCHASE_LOCK_KEY_YELLOW",
		"Желтый ключ от запертой двери",
		"Yellow key for locked door",
		"PURCHASE_LOCK_KEY_BLUE",
		"Синий ключ от запертой двери",
		"Blue key for locked door",
		"PURCHASE_LOCK_KEY_GREEN",
		"Зеленый ключ от запертой двери",
		"Green key for locked door",
		"PURCHASE_LOCK_KEY_WHITE",
		"Белый ключ от запертой двери",
		"White key for locked door",
		"PURCHASE_TILE_CUBES",
		"Кубы крыши",
		"Roof blocks",
		"PURCHASE_CASTLE_CUBES",
		"Замок",
		"Castle blocks",
		"PURCHASE_DUNGEON_CUBES",
		"Подземелье",
		"Dungeon blocks",
		"PURCHASE_FORTRESS_CUBES",
		"Крепость",
		"Fortress blocks",
		"PURCHASE_LIBRARY_CUBES",
		"Библиотека",
		"Library blocks",
		"PURCHASE_TAVERN_CUBES",
		"Таверна",
		"Tavern blocks",
		"PURCHASE_MILITARY_CUBES",
		"Военная база",
		"Military blocks",
		"PURCHASE_MILITARY_ARMORY",
		"Военный арсенал",
		"Military armory",
		"PURCHASE_MILITARY_BARREL",
		"Военная бочка ",
		"Military barrel",
		"PURCHASE_MILITARY_BED",
		"Военная кровать",
		"Military bed",
		"PURCHASE_MILITARY_CAM",
		"Военная камера",
		"Military cam",
		"PURCHASE_MILITARY_CASE_BIG",
		"Военный большой шкаф",
		"Military big case",
		"PURCHASE_MILITARY_CASE_SMALL",
		"Военный шкаф",
		"Military case",
		"PURCHASE_MILITARY_CHAIR",
		"Военный стул",
		"Military chair",
		"PURCHASE_MILITARY_CHEST",
		"Военный сундук",
		"Military chest",
		"PURCHASE_MILITARY_CONSOLE_01",
		"Военная консоль 1",
		"Military console 1",
		"PURCHASE_MILITARY_CONSOLE_02",
		"Военная консоль 2",
		"Military console 2",
		"PURCHASE_MILITARY_CONSOLE_03",
		"Военная консоль 3 ",
		"Military console 3",
		"PURCHASE_MILITARY_DOOR",
		"Военная дверь",
		"Military door",
		"PURCHASE_MILITARY_LAMP",
		"Военная лампа",
		"Military lamp",
		"PURCHASE_MILITARY_LANTERN",
		"Военный фонарь",
		"Military lantern",
		"PURCHASE_MILITARY_MUG",
		"Военная кружка",
		"Military mug",
		"PURCHASE_MILITARY_PC",
		"Военный компьютер",
		"Military PC",
		"PURCHASE_MILITARY_TABLE_BIG",
		"Военный большой стол",
		"Military big table",
		"PURCHASE_MILITARY_TABLE_SMALL",
		"Военный стол",
		"Military table",
		"PURCHASE_MILITARY_FENCE",
		"Военное ограждение",
		"Military fence",
		"PURCHASE_MILITARY_BENCH",
		"Военная скамья",
		"Military bench",
		"PURCHASE_MILITARY_BOX_01",
		"Военный ящик 1",
		"Military box 1",
		"PURCHASE_MILITARY_BOX_02",
		"Военный ящик 2",
		"Military box 2",
		"PURCHASE_MILITARY_BRIEFING_BOARD",
		"Военная доска брифинга",
		"Military briefing board",
		"PURCHASE_ARCHER_SKIN",
		"Лучник",
		"Archer",
		"PURCHASE_TERRORIST_SKIN",
		"Террорист",
		"Terrorist",
		"PURCHASE_COOK_SKIN",
		"Повар",
		"Cook",
		"PURCHASE_DARK_STALKER_SKIN",
		"Темный сталкер",
		"Dark Stalker",
		"PURCHASE_MERCENARY_SKIN",
		"Наемник",
		"Mercenary",
		"PURCHASE_SMELTER_SKIN",
		"Кузнец",
		"Smelter",
		"PURCHASE_AMMUNITION",
		"Патроны",
		"Ammunition",
		"PURCHASE_FLAG_RED",
		"Красный флаг",
		"Red Flag",
		"PURCHASE_FLAG_BLUE",
		"Синий флаг",
		"Blue Flag",
		"PURCHASE_GRENADE_LAUNCHER2",
		"Простой гранатомет",
		"Simple Grenade Launcher",
		"PURCHASE_LUGER",
		"Люгер",
		"Luger",
		"PURCHASE_REVOLVER",
		"Кольт Анаконда",
		"Colt Anaconda",
		"PURCHASE_COLT",
		"Дезерт Игл",
		"Desert Eagle",
		"PURCHASE_SAWN_OFF",
		"Обрез",
		"Sawed off Shotgun",
		"PURCHASE_WINCHESTER",
		"Винчестер",
		"Winchester",
		"PURCHASE_SVD",
		"SVD",
		"SVD",
		"PURCHASE_WEAPON_SG552",
		"SG552",
		"SG552",
		"PURCHASE_SG550",
		"SG550",
		"SG550",
		"PURCHASE_AUG",
		"AUG",
		"AUG",
		"PURCHASE_DARK_CASTLE_CUBES",
		"Темный замок",
		"Dark castle",
		"PURCHASE_INDUSTRIAL_CUBES",
		"Фабрика",
		"Industrial blocks",
		"PURCHASE_DESC_FLOWERS1",
		"Цветы 1 уровня",
		"Flowers Level 1",
		"PURCHASE_DESC_FLOWERS2",
		"Цветы 2 уровня",
		"Flowers Level 2",
		"PURCHASE_DESC_FLOWERS3",
		"Цветы 3  уровня",
		"Flowers Level 3",
		"PURCHASE_DESC_WOODEN_BLOCKS",
		"Пак деревянных кубов 1 уровня",
		"Pak wooden cubes 1 level",
		"PURCHASE_DESC_STONE_BLOCKS",
		"Пак каменных кубов 1 уровня",
		"Pak stone cubes 1 level",
		"PURCHASE_DESC_STONE_BLOCKS",
		"Пак каменных кубов 2 уровня",
		"Pak stone cubes 2 levels",
		"PURCHASE_DESC_COLORED_BLOCKS",
		"Пак цветных кубов для строительства",
		"Pak colored cubes to build",
		"PURCHASE_DESC_GLASS_BLOCKS",
		"Пак прозрачных стеклянных кубов",
		"Pak transparent glass cubes",
		"PURCHASE_DESC_GRATES_BLOCKS",
		"Пак решеток",
		"Pak lattices",
		"PURCHASE_DESC_ICE_BLOCK",
		"Скользкий блок",
		"Sliding block",
		"PURCHASE_DESC_LAVA_BLOCK",
		"Наносит урон игрокам находящимся рядом с блоком лавы",
		"Deals damage to nearby players with a block of lava",
		"PURCHASE_DESC_WATER_BLOCK",
		"Физичный блок в котором можно плавать",
		"Physicality block where you can swim",
		"PURCHASE_DESC_TRAMPOLINE_BLOCK",
		"Отталкивает вас вверх",
		"It pushes you up",
		"PURCHASE_DESC_RESTORE_BLOCK",
		"Падает когда по нему прошли",
		"It falls when it passed",
		"PURCHASE_DESC_TEAM_BLOCKS",
		"Неразрушимы никаким оружием, служат для создания безопасных зон на командных респаунах",
		"Indestructible by any weapon, used to create safe zones in the team respawn",
		"PURCHASE_DESC_SPEED_POTION",
		"Позволяет копателю быстрее передвигаться по карте. ",
		"Allows diggers quickly move around the map",
		"PURCHASE_DESC_FLIGHT_POTION",
		"Позволяет копателю летать",
		"Allows diggers fly",
		"PURCHASE_DESC_TELEPORT",
		"Позволяет телепортироваться к другим игрокам",
		"Allows you to teleport to other players",
		"PURCHASE_DESC_DYNAMITE",
		"Служит для быстрой расчистки местности",
		"It allows for quick clearance area",
		"PURCHASE_DESC_AIR_BOMB",
		"Наносит увеличенные повреждения",
		"Inflicts increased damage",
		"PURCHASE_DESC_RESPAWN",
		"Укажите где будут появляться игроки на вашей карте. На карте может быть только 1 точка появления игроков.",
		"Specify where the players will appear on your map. The map can be only one point of visiting players.",
		"PURCHASE_DESC_TEAM_RESPAWN",
		"Укажите где будут появляться игроки на вашей карте при командной игре.",
		"Specify where the players will appear on your map at the team game.",
		"PURCHASE_DESC_BLOAT",
		"На лодке можно плавать",
		"On the boat you can swim",
		"PURCHASE_DESC_ADV_SMILES",
		"В пак входит 12 допольнительных стикеров",
		"The package includes 12 additional emotions",
		"PURCHASE_DESC_MEM_FACES",
		"Пак популярных мем фейсов",
		"Pak popular meme face",
		"PURCHASE_DESC_RAILS",
		"В покупку входит 12 рельс",
		"The purchase includes 12 rail",
		"PURCHASE_DESC_DAY_NIGHT",
		"Возможность установки дня или ночи",
		"Ability to set the day or night",
		"PURCHASE_DESC_GOLD_CUP",
		"Спрячьте в тайных местах вашей карты кубки, игроки должны найти их!",
		"Hide in secret places of your card Cups, players have to find them!",
		"PURCHASE_DESC_TEAM_DOORS",
		"Пропускают только игроков своей команды",
		"Pass only the players of his team",
		"PURCHASE_DESC_SIGNPOST",
		"Декорации 1 уровня",
		"Scenery 1 level",
		"PURCHASE_DESC_STAIRS",
		"Деревянные ступеньки",
		"Wooden stairs",
		"PURCHASE_DESC_STAIRS",
		"Каменные ступеньки",
		"Stone steps",
		"PURCHASE_DESC_WALL_TORCH",
		"Факел может осветить темные места",
		"The torch can light up dark places",
		"PURCHASE_DESC_FLOOR_TORCH",
		"Факел может осветить темные места",
		"The torch can light up dark places",
		"PURCHASE_DESC_FLOOR_PLATE",
		"На табличке можно написать любую информацию, которую увидят другие игроки",
		"The plate can be written with any information they see other players",
		"PURCHASE_DESC_WALL_PLATE",
		"На табличке можно написать любую информацию, которую увидят другие игроки",
		"The plate can be written with any information they see other players",
		"PURCHASE_DESC_BOOK",
		"В книге можно писать текст. Написанные книги могут читать другие игроки",
		"In the book, you can write text. Wrote a book can read other players",
		"PURCHASE_DESC_LADDER",
		"Позволяет забираться на  блоки  вертикально",
		"Lets get on the blocks vertically",
		"EMOTION_HAPPY",
		"Радуется",
		"Happy",
		"EMOTION_SAD",
		"Расстроен",
		"Sad",
		"EMOTION_YES",
		"Да",
		"Yes",
		"EMOTION_NO",
		"Нет",
		"No",
		"EMOTION_QUESTION",
		"Вопрос",
		"Question",
		"EMOTION_EXCLAMATION",
		"!!!",
		"!!!",
		"EMOTION_SUPRISED",
		"Удивлен",
		"Suprised",
		"EMOTION_ANGRY",
		"Злится",
		"Angry",
		"EMOTION_FUN",
		"Веселится",
		"Fun",
		"EMOTION_CRYING",
		"Плачет",
		"Crying",
		"EMOTION_LOVE",
		"Влюблен",
		"Love",
		"EMOTION_SICK",
		"Тошнит",
		"Sick",
		"EMOTION_DEATH",
		"Смерть",
		"Death",
		"EMOTION_TEASES",
		"Показывает язык",
		"Teases",
		"EMOTION_HAPPY2",
		"Счастлив",
		"Happy",
		"EMOTION_ALLOW",
		"За",
		"Allow",
		"EMOTION_DENY",
		"Против",
		"Deny",
		"EMOTION_STRENGTH",
		"Сила",
		"Strength",
		"EMOTION_LOL",
		"LOL",
		"LOL",
		"EMOTION_HAPPY3",
		"Счастлив",
		"Happy",
		"EMOTION_ALONE",
		"Forever alone",
		"Forever alone",
		"EMOTION_OK",
		"Okay",
		"Okay",
		"EMOTION_PLEASE",
		"Please",
		"Please",
		"EMOTION_TROLL_FACE",
		"Troll Face",
		"Troll Face",
		"EMOTION_KIDDING",
		"Издеваешься?",
		"Kidding me?",
		"EMOTION_ALONE2",
		"Forever alone счастлив",
		"Forever alone happy",
		"EMOTION_FUUU",
		"Fuuuuuuu",
		"Fuuuuuuu",
		"EMOTION_HMM",
		"Hmm...",
		"Hmm...",
		"EMOTION_CHALLENGE",
		"Challenge accepted",
		"Challenge accepted",
		"TILE_CUBES",
		"Крыша",
		"Roof",
		"CASTLE_CUBES",
		"Замок",
		"Castle",
		"DUNGEON_CUBES",
		"Подземелье",
		"Dungeon",
		"FORTRESS_CUBES",
		"Крепость",
		"Fortress",
		"LIBRARY_CUBES",
		"Библиотека",
		"Library",
		"TAVERN_CUBES",
		"Таверна",
		"Tavern",
		"CHEATING_LOW_PLAYERS",
		"Нужно больше игроков для голосования",
		"Need more players for voting",
		"CHEATING_ALREADY_STARTED",
		"Голосование уже начато",
		"Voting already started",
		"CHEATING_STARTED1",
		"Голосование начато: игрок ",
		"Voting beginning: player ",
		"CHEATING_STARTED2",
		" читер? Нажмите Д или Н",
		" cheater? Press Y or N",
		"CHEATING_END_CHEATER",
		"Голосование окончено, игрок читер",
		"Voting ended, player is cheater",
		"CHEATING_END_NOT_CHEATER",
		"Голосование окончено, игрок не читер",
		"Voting ended, player is not cheater",
		"CHEATING_VOTE1",
		"Игрок ",
		"Player ",
		"CHEATING_VOTE2",
		" думает ",
		" think ",
		"CHEATING_VOTE_YES",
		"ДА",
		"YES",
		"CHEATING_VOTE_NO",
		"НЕТ",
		"NO",
		"LEVEL_TITLE",
		"УРОВЕНЬ",
		"LEVEL",
		"LEVEL_1",
		"1-Новобранец",
		"1-Rookie",
		"LEVEL_2",
		"2-Рядовой",
		"2-Private",
		"LEVEL_3",
		"3-Наемник",
		"3-Mercenary",
		"LEVEL_4",
		"4-Страж",
		"5-Guard",
		"LEVEL_5",
		"5-Боец",
		"5-Fighter",
		"LEVEL_6",
		"6-Воитель",
		"6-Warmaster",
		"LEVEL_7",
		"7-Мастер",
		"7-Master",
		"LEVEL_8",
		"8-Гвардеец",
		"8-Guardsman",
		"LEVEL_9",
		"9-Гвардейский защитник",
		"9-Guards defender",
		"LEVEL_10",
		"10-Гвардейский оружейник",
		"10-Guards gunsmith",
		"LEVEL_11",
		"11-Ветеран гвардии",
		"11-Veteran Guards",
		"LEVEL_12",
		"12-Бесстрашный",
		"12-Fearless",
		"LEVEL_13",
		"13-Неудержимый",
		"13-Irresistible",
		"LEVEL_14",
		"14-Герой",
		"14-Hero",
		"LEVEL_15",
		"15-Аватар войны",
		"15-Avatar War",
		"LEVEL_16",
		"16-Завоеватель",
		"16-Conqueror",
		"LEVEL_17",
		"17-Мистический воин",
		"17-Mystic Warrior",
		"LEVEL_18",
		"18-Призрак",
		"18-Ghost",
		"LEVEL_19",
		"19-Призрак рока",
		"19-Ghost Rock",
		"LEVEL_20",
		"20-Десница рока",
		"20-Hand of fate",
		"LEVEL_21",
		"21-Мастер над оружием",
		"21-Master of Arms",
		"LEVEL_22",
		"22-Неуязвимый",
		"22-Unbreakable",
		"LEVEL_23",
		"23-Лорд",
		"23-Lord",
		"LEVEL_24",
		"24-Лорд-хранитель",
		"24-Lord-Guardian",
		"LEVEL_25",
		"25-Лорд-командующий",
		"25-Lord-Commander",
		"LEVEL_26",
		"26-Повелитель",
		"26-Overlord",
		"LEVEL_27",
		"27-Повелитель над оружием",
		"27-Lord of Arms",
		"LEVEL_28",
		"28-Принц-воитель",
		"28-Prince-warrior",
		"LEVEL_29",
		"29-Бессмертный воин",
		"29-Immortal Warrior",
		"LEVEL_30",
		"30-Повелитель смерти",
		"30-Lord of Death",
		"PURCHASE_BLOCK_KIND_QUARTER",
		"Четверть",
		"Quarter",
		"ENTER_SLOT_NAME_DESC",
		"Введите название слота",
		"Enter slot name",
		"ENTER_SLOT_NAME",
		"Название",
		"Slot name",
		"wUnior_Knight_Sword",
		"Деревянный\nмеч",
		"Wooden \nsword",
		"wKnight_Sword",
		"Железный\nмеч",
		"Iron \nsword",
		"wEpic_Knight_Sword",
		"Эпичный\nмеч",
		"Epic \nsword",
		"wDeath_Knight_Sword",
		"Меч темного\nрыцаря",
		"Dark \nsword",
		"wViking_Axe",
		"Топор\nвикинга",
		"Viking \nax",
		"wUnior_Knight_Bow",
		"Деревянный\nЛук",
		"Wooden \nbow",
		"wKnight_Bow",
		"Железный\nЛук",
		"Iron \nbow",
		"wEpic_Knight_Bow",
		"Эпичный\nЛук",
		"Epic \nbow",
		"wDeath_Knight_Bow",
		"Лук темного\nрыцаря",
		"Dark \nbow",
		"fCheese",
		"Сыр",
		"Сheese",
		"fFish",
		"Рыба",
		"Fish",
		"fMeat",
		"Кусок мяса",
		"Piece of meat",
		"fChicken",
		"Курица",
		"Chicken",
		"fPig",
		"Свинина",
		"Pork",
		"wUnior_Knight_Quiver",
		"Деревянные\nстрелы",
		"Wooden \narrows",
		"wKnight_Quiver",
		"Железные\nстрелы",
		"Iron \narrows",
		"wEpic_Knight_Quiver",
		"Эпичные\nстрелы",
		"Epic \narrows",
		"wDeath_Knight_Quiver",
		"Стрелы\nТемного Рыцаря",
		"Dark \narrows",
		"skin_archer",
		"Начинающий\nлучник",
		"Beginner \narcher",
		"skin_unior_knight",
		"Новобранец\nрыцарей",
		"knights \nrookie",
		"skin_viking",
		"Викинг",
		"Viking",
		"skin_knight",
		"Рыцарь",
		"Knight",
		"skin_epic_knight",
		"Эпичный\nрыцарь",
		"Epic \nknight",
		"skin_death_knight",
		"Рыцарь\nсмерти",
		"Dark \nknight",
		"tt_Defense",
		"Броня",
		"Arrmor",
		"tt_Attack",
		"Сила удара",
		"Attack Pwr",
		"tt_Medication",
		"Лечению",
		"Medication",
		"tt_Atk_Bonus",
		"Бонус атаки",
		"Attack Bonus",
		"hg_Left_to_spawn",
		"До перемещения: ",
		"Left to spawn ",
		"hg_start_battle_after",
		"До начала битвы: ",
		"The start battle after ",
		"hg_fight_in_the_arena",
		"До переноса на арену: ",
		"Arena start after: ",
		"hg_start_the_arena",
		"До начала битвы на арене осталось ",
		"Start the arena after ",
		"hg_in_the_attack",
		"Игра началась!",
		"The game started!",
		"arcade_in_the_attack",
		"Беги!!!",
		"Run!",
		"hg_winner_is",
		"Победитель: ",
		"Winner: ",
		"hg_arena_is_start",
		"Бой на арене!",
		"Fight in the arena!",
		"PURCHASE_HG_APOS_SPAWN_POINT",
		"Постамент",
		"Plinth",
		"PURCHASE_HG_ARENA_SPAWN_POINT",
		"Флаг арены",
		"Arena flag",
		"PURCHASE_HG_ARCHER1",
		"Набор лучника 1",
		"Archer Build Level 1",
		"PURCHASE_HG_ARCHER2",
		"Набор лучника 2",
		"Archer Build Level 2",
		"PURCHASE_HG_ARCHER3",
		"Набор лучника 3",
		"Archer Build Level 3",
		"PURCHASE_HG_ARCHER4",
		"Набор лучника 4",
		"Archer Build Level 4",
		"PURCHASE_HG_ARCHER5",
		"Набор лучника 5",
		"Archer Build Level 5",
		"PURCHASE_HG_KNIGHT1",
		"Набор рыцаря 1",
		"Knight Build Level 1",
		"PURCHASE_HG_KNIGHT2",
		"Набор рыцаря 2",
		"Knight Build Level 1",
		"PURCHASE_HG_KNIGHT3",
		"Набор рыцаря 3",
		"Knight Build Level 1",
		"PURCHASE_HG_KNIGHT4",
		"Набор рыцаря 4",
		"Knight Build Level 1",
		"PURCHASE_HG_KNIGHT5",
		"Набор рыцаря 5",
		"Knight Build Level 1",
		"STORE_HUNGRY_GAMES",
		"НАБОРЫ ДЛЯ ГОЛОДНЫХ ИГР",
		"Hungry Games",
		"HG_PACK",
		"Паки Голодных игр",
		"Hungry Games Packs",
		"SELECT_PACK",
		"Выберите пак для игры",
		"Select Pack To Game",
		"MY_MAPS_SAVE_Q",
		"СОХРАНИТЬ КАРТУ?",
		"SAVE MAP?",
		"WAIT_PLAYER_TO_START",
		"Ожидание игроков: ",
		"Waiting for players ",
		"ITEM_FROM_PACK",
		", + ",
		", + ",
		"ADD_EXP_FO_KILL",
		"+5 к опыту",
		"+5 Exp",
		"HG_START_CLOSE",
		"Игра идет (Закрыто)",
		"Game is started (Closed)",
		"HG_GET_GUILD_MSG",
		"Через 10 секунд вы получите : ",
		"After 10 seconds you get : ",
		"HG_GET_GUILD_SET_MSG",
		"Вы получили набор : ",
		"You Get pack : ",
		"HG_ADD_GOLD_GAME",
		" золота в конце игры",
		" gold at the end of the game",
		"GAME_MONTH_ACCUSATIVE",
		",Января,Февраля,Марта,Апреля,Мая,Июня,Июля,Августа,Сентября,Октября,Ноября,Декабря",
		",January,February,March,April,May,June,July,August,September,October,November,December",
		"CAT_CARPET",
		"Ковры",
		"Carpets",
		"PURCHASE_CARPET_01",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_02",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_03",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_04",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_05",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_06",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_07",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_08",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_09",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_10",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_11TH",
		"Ковер",
		"Carpet",
		"PURCHASE_CARPET_11TV",
		"Ковер",
		"Carpet",
		"SPAWN_MIN_DISTANCE",
		"Дистанция между точками появления очень маленькая",
		"The distance between the points of occurrence is very small",
		"HG_APOS_SPAWN_POINT_NO_EXIST_ALL",
		"Не хватает опостаментов для появленяи, должно быть 8",
		"Not enough for opostamentov poyavlenyai must be 8",
		"HG_ARENA_SPAWN_POINT_NO_EXIST",
		"Не установлен флаг арены",
		"Do not set the flag of the arena",
		"CHEAT_USE_speed_cheat",
		"Вы использовали чит на скорость",
		"You use speed cheat",
		"CHEAT_USE_lawa_cheat",
		"Вы использовали чит что бы стоять на лаве",
		"You use lava cheat",
		"CHEAT_USE_fly_cheat",
		"Вы использовали чит на полет",
		"You use fly cheat",
		"CHEAT_USE_wall_cheat",
		"Вы использовали чит на проход сквозь стены",
		"You use wall cheat",
		"CHEAT_USE_invalide_object_use",
		"Вы использовали чит на использование не купленных предметов",
		"You use no buy item cheat",
		"CHEAT_USE_zombie_block_cheat",
		"Вы использовали чит на установку кубиков для зомби сверх лимита",
		"You use zombie box add cheat",
		"CHEAT_USE_life_is_no_correct",
		"Вы использовали чит добавляющий вам жизни",
		"You use add life cheat",
		"CHEAT_USE_voting_players",
		"Другие игроки проголосовали что Вы читер",
		"Players Say - You Cheater",
		"KIKED_FROM_CHEAT",
		"выкинут за читы",
		"kick From Cheat",
		"ARCADE_PLACE_TXT",
		"Вы заняли %PLACE% место",
		"You get %PLACE% place",
		"PURCHASE_RESTORE_BLOCK",
		"Опадающий блок",
		"Block restore",
		"CHAT_MSG_GOLD",
		"к золоту",
		" gold",
		"CHAT_MSG_EXP",
		"к опыту",
		" xp",
		"ARCADE_PLAYER_LOST",
		"Игроков: %COUNT%",
		"Players: %COUNT%",
		"ARCADE_SPEED_LOST",
		"Скорость: x%SPEED%",
		"Speed: x%SPEED%",
		"CHEATING_TIMEOUT",
		"Для начала нового голосования нужно немного подождать",
		"To begin voting again have to wait a little longer",
		"HS_TEAM",
		"Выбор стороны",
		"Select Side",
		"SELECT_SIDE",
		"Выберите команду",
		"Select Team",
		"SELECT_HIDE",
		"Прячущиеся",
		"Hidened",
		"SELECT_SEEK",
		"Ищущие",
		"Seekened",
		"HIDEINING_PROCESS",
		"ПРЯЧЕМСЯ...",
		"HIDINING...",
		"HS_ITEM",
		"Выбор маскировки",
		"Selecting masking",
		"SELECT_HS_ITEM",
		"Во что будете маскироваться?",
		"What will be masked?",
		"DIRT_BOX",
		"Ландшафт грязь",
		"The landscape of the mud",
		"ITEM_CHAIR",
		"Вещи стул",
		"Things chair",
		"HS_NOW_HIDE",
		"Что бы спрятаться осталось {0} секунд",
		"To hide left {0} sec",
		"HS_TIME_TO_SEEK",
		"Время искать!",
		"Time to Seek!",
		"HS_NO_START_POINT",
		"На карте не установлена точка старта",
		"The map does not set the starting point",
		"HS_NO_HIDE_POINT",
		"На карте не установлен крастный старт для команды прячущихся",
		"The map is not set for the start of the red team hiding",
		"HS_NO_SEEK_POINT",
		"на карте не установлен синий спавн для команды ищущих",
		"Map is not installed blue spawn for the team looking for",
		"HS_PLUS_2",
		"+ 5 к награде",
		"+ 5 for the award",
		"HS_WAIT_END_WISP",
		"До перезарядки умения осталось {0} секунд",
		"Before cooldown remaining {0} seconds",
		"HS_PLAYER_SEEKING",
		"Игрока {0} Нашли, теперь он ищущий",
		"Player {0} Found, now he seeks",
		"HS_HIDE_COUNT",
		"Осталось {0} прячущихся",
		"Left {0} hiding ",
		"AMBIENT_OCCLUSION",
		"ПЛАВНОЕ ОСВЕЩЕНИЕ",
		"AMBIENT OCCLUSION",
		"PURCHASE_BLOCK_KIND_STAIR_CORNER",
		"Угловая лестница",
		"Corner stair",
		"BLOOM",
		"СВЕЧЕНИЕ",
		"BLOOM",
		"SETTINGS_LANGUAGE",
		"ЯЗЫК",
		"LANGUAGE",
		"LANGUAGE_RU",
		"Русский",
		"RUSSIA",
		"LANGUAGE_EN",
		"Английский",
		"ENGLISH",
		"PURCHASE_CITY_INTERIOR",
		"Городской интерьер",
		"City Interior",
		"PURCHASE_CITY_EXTERIOR",
		"Городской экстерьер",
		"City Exterior",
		"PURCHASE_CE_ATTENTION_BOARD",
		"Заградитель",
		"Attention Board",
		"PURCHASE_CE_BIG_GARBAGE_BOX_CLOSE",
		"Мусорка",
		"Garbage",
		"PURCHASE_CE_BIG_GARBAGE_BOX_OPEN",
		"Мусорка",
		"Garbage",
		"PURCHASE_CE_BIG_STREET_LANTERN",
		"Уличный Фонарь",
		"Street lantern",
		"PURCHASE_CE_CONE",
		"Конус",
		"Cone",
		"PURCHASE_CE_FG",
		"Пожарный столб",
		"Fire column",
		"PURCHASE_CE_GARBAGE_BOX",
		"Мусорка",
		"Garbage box",
		"PURCHASE_CE_MAIL_BOX",
		"Почтовый ящик",
		"Mail box",
		"PURCHASE_CE_METAL_DOOR",
		"Металлическая дверь",
		"Metal Door",
		"PURCHASE_CE_PHONEBOX",
		"Телефонная будка",
		"Phonebox",
		"PURCHASE_CE_SMALL_SREET_LANTERN",
		"Маленький фонарь",
		"Street lantern",
		"PURCHASE_CE_STREET_BENCH",
		"Скамейка",
		"Bench",
		"PURCHASE_CE_STREET_CLOCK",
		"Уличные часы",
		"Street Clock",
		"PURCHASE_CE_STREET_LADDER",
		"Уличная лестница",
		"Street Ladder",
		"PURCHASE_CE_WOOD_DOOR",
		"Деревянная дверь",
		"Wood door",
		"PURCHASE_CI_BATH",
		"Ванна",
		"Bath",
		"PURCHASE_CI_BED",
		"Кровать",
		"Bed",
		"PURCHASE_CI_BEDROOM_CASE",
		"Тумбочка",
		"Bedroom case",
		"PURCHASE_CI_BEDROOM_LAMP",
		"Лампа",
		"Bedroom lamp",
		"PURCHASE_CI_BIG_LAMP",
		"Люстра",
		"Big lamp",
		"PURCHASE_CI_BOWL",
		"Тарелка",
		"Bowl",
		"PURCHASE_CI_COFFEE_CUP",
		"Кружка",
		"Coffee cup",
		"PURCHASE_CI_DOOR",
		"Дверь",
		"Door",
		"PURCHASE_CI_KITCHEN_BOARD",
		"Кухонная доска",
		"Kitchen Board",
		"PURCHASE_CI_KITCHEN_CHAIR",
		"Стул",
		"Kitchen chair",
		"PURCHASE_CI_KITCHEN_PART",
		"Тумбочка",
		"Kithen part",
		"PURCHASE_CI_KITCHEN_PART_CORNER",
		"Тумбочка",
		"Kitchen part corner",
		"PURCHASE_CI_KITCHEN_TABLE",
		"Стол",
		"Kitchen table",
		"PURCHASE_CI_KITCHEN_WASHING",
		"Раковина",
		"Kitchen washing",
		"PURCHASE_CI_WLAPTOP",
		"Ноутбук",
		"Laptop",
		"PURCHASE_CI_LOUDSPEAKERS",
		"Колонки",
		"Loudspeakers",
		"PURCHASE_CI_MICROWAVE",
		"Микроволновка",
		"Microwave",
		"PURCHASE_CI_OFFICE_CHAIR",
		"Офисный стул",
		"Office chair",
		"PURCHASE_CI_OFFICE_LAMP",
		"Офисная лампа",
		"Office lamp",
		"PURCHASE_CI_OFFICE_TABLE",
		"Офисный стол",
		"Office table",
		"PURCHASE_CI_OFFICE_CASE",
		"Офисная тумбочка",
		"Office case",
		"PURCHASE_CI_OVEN",
		"Духовка",
		"Oven",
		"PURCHASE_CI_PLATE",
		"Тарелка",
		"Plate",
		"PURCHASE_CI_REFRIGERATOR",
		"Холодильник",
		"Refrigerator",
		"PURCHASE_CI_SAUCER",
		"Тарелка",
		"Saucer",
		"PURCHASE_CI_SHOWER",
		"Душ",
		"Shower",
		"PURCHASE_CI_SMALL_LAMP",
		"Люстра",
		"Small lamp",
		"PURCHASE_CI_SMALL_TABLE",
		"Стеклянный стол",
		"Small table",
		"PURCHASE_CI_SOAP",
		"Мыло",
		"Soap",
		"PURCHASE_CI_SOFA",
		"Диван",
		"Sofa",
		"PURCHASE_CI_SOFT_CHAIR",
		"Кресло",
		"Soft chair",
		"PURCHASE_CI_TV",
		"Телевизор",
		"TV",
		"PURCHASE_CI_WARDROBE",
		"Шкаф",
		"Wardrobe",
		"PURCHASE_CI_WASHBASIN",
		"Раковина",
		"Washbasin",
		"PURCHASE_CI_WWASHING_MACHINE",
		"Стиральная машина",
		"Washing machine",
		"PURCHASE_CI_WC",
		"Туалет",
		"WC",
		"LBL_SAVE",
		"СОХРАНЕНИЕ",
		"SAVE",
		"LBL_ALERT",
		"ВНИМАНИЕ",
		"ALERT",
		"LBL_ALERT_3CHAR",
		"Название комнаты должно быть больше 3 букв",
		"The name of the room should be more than 3 letters",
		"LBL_ALERT_NO_REGENERATE",
		"Нельзя перегенерировать карту пока на ней кто-либо играет",
		"You can not rebuild the map until it anyone plays",
		"LBL_ALERT_NAME_EXIST",
		"Комната с таким названием существует",
		"A room with that name exists",
		"RECOMENDED_WORLD",
		"Рекомендуемый мир",
		"Recommended world",
		"CHEATER_QUESTIONS",
		"Считаете ли вы игрока {0} читером\n",
		"Do you think the player {0} cheater ",
		"CHEATER_QUESTIONS2",
		"Да - нажмите клавишу Д\nНет - нажмите клавишу Н\n",
		"Yes - press the L \nNet - press Y \n",
		"CHEATER_YES",
		"Да",
		"Yes",
		"CHEATER_NO",
		"Нет",
		"No",
		"CHEATER_TIME",
		"До конца голосования осталось {0} секунд",
		"Until the end of voting left {0} seconds",
		"NAME_WAREHOUSE",
		"СКЛАД",
		"WAREHOUSE",
		"MY_MAPS_ADD_SLOT",
		"ДОБАВИТЬ СЛОТ",
		"ADD SLOT",
		"GET_ITEM_FREE",
		"ПОЛУЧИТЬ",
		"GET ITEM",
		"FREE_TXT",
		"Бесплатно",
		"Free",
		"PURCHASE_NY_TREE",
		"Новогодняя Елка",
		"New Year Tree",
		"PURCHASE_SANTA_SKIN",
		"Новогодний копатель",
		"New Year digger",
		"MAP_NAME_ERROR",
		"Название карты не может быть более 15 символов",
		"The name of the map can not be more than 15 characters",
		"MAP_VOTE_ERROR",
		"Для начала голосования необходим 12 уровень",
		"To begin voting required 12START_SERVERS_LIST level",
		"PURCHASE_NBBLU",
		"Голубой блок",
		string.Empty,
		"PURCHASE_NBGRAY",
		"Серый блок",
		string.Empty,
		"PURCHASE_NBDARKGREY",
		"Темно-серый блок",
		string.Empty,
		"PURCHASE_NBBROWN",
		"Коричневый блок",
		string.Empty,
		"PURCHASE_NBBEIGE",
		"Бежевый блок",
		string.Empty,
		"PURCHASE_NBKHAKI",
		"Хаки блок",
		string.Empty,
		"SHOW_CLOSE_SERVER",
		"Отображать заполненные сервера",
		"Dont display full server",
		"CHEAT_VOTE_ERROR_MYSELF",
		"Нельзя начать голосование против самого себя",
		"You can not start voting against himself",
		"CHEAT_STARTER_NAME",
		"Голосование начал:",
		"Vote start:",
		"STORE_WEAPON_SKIN",
		"СКИНЫ ОРУЖИЙ",
		"Weapon Skins:",
		"STORE_WEAPON_SKIN",
		"Скины оружий",
		"Weapon Skins",
		"SHOP_TAKEOFF",
		"Снять",
		"Take off",
		"NO_M16_WEAPON_ERROR",
		"Для покупки вам необходимо приобрести Автомат М4А",
		"To purchase you need to purchase M4A Machine",
		"INSTRUMENTS",
		"Инструменты",
		"Instruments",
		"TRANSPORT_INSTRUMENTS",
		"Транспорт",
		"Transport",
		"ERROR_NAME_CHAR",
		"Ник может содержать: буквы, цифры, дефисы и подчёркивания",
		"Nick can contain: letters, numbers, dashes and underscores",
		"FISH_CATEGORY",
		"Рыбы",
		"Fish",
		"CAT_CATEGORY",
		"Кошки",
		"Cats",
		"PURCHASE_NY_16_TREE",
		"Новогодняя ёлка",
		"Christmas Tree",
		"PURCHASE_NY_16_BIG_TREE",
		"Ёлка",
		"Tree",
		"PURCHASE_NY_16_SNOWMAN",
		"Снеговик",
		"Snowman",
		"PURCHASE_NY_16_GIFT",
		"Подарок",
		"Gift",
		"PURCHASE_NY_16_GIFT_BAG",
		"Мешок подарков",
		"Gift bag",
		"PURCHASE_NY_16_SOCK",
		"Носок",
		"Sock",
		"PURCHASE_NY_16_WREATH",
		"Венок",
		"Wreath",
		"VERSION_TEXT",
		"Версия",
		"Version",
		"ACTION_BUY_TEXT",
		"Купить",
		"Buy",
		"CHANGE_WORLD",
		"Сменить мир",
		"Change world",
		"HOME_PLANTS_CAT",
		"Комнатные растения",
		string.Empty,
		"MUSHROOMS",
		"Грибы",
		"Mushrooms",
		"SC_MAP_SIZE",
		"Размеры карт",
		"Dimensions of maps",
		"SC_MAP_TYPE",
		"Типы карт",
		"Types of maps",
		"WCAT_AK47",
		"АК47",
		"АК47",
		"WCAT_SWD",
		"SVD",
		"SVD",
		"WCAT_GLOCK",
		"Глок 18",
		"Glock 18",
		"WCAT_M16",
		"М4А",
		"М4А",
		"WCAT_M1014",
		"SWAT shotgun",
		"SWAT shotgun",
		"WCAT_SG553",
		"SG552",
		"SG552",
		"WCAT_GLAUNCHER",
		"Гранатомет",
		"Grenade-gun",
		"WCAT_MP5",
		"MP5",
		"MP5",
		"WCAT_AUG",
		"AUG",
		"AUG",
		"WCAT_SG550",
		"SG550",
		"SG550",
		"WCAT_SAWN_OFF",
		"Обрез",
		"SawnOff",
		"PURCHASE_KIRCKA",
		"Улучшенная кирка",
		"Improved pickaxe",
		"PURCHASE_SUPER_KIRCKA",
		"Супер кирка",
		"Super pickaxe",
		"PURCHASE_DIGPOOL",
		"Дигпул",
		"Digpool",
		"PURCHASE_PL_CACTUS",
		"Кактус",
		"Cactus",
		"PURCHASE_PL_WATERLILY",
		"Лилия",
		"Lily",
		"PURCHASE_PL_WATERLILY2",
		"Кувшинка",
		"Water lily",
		"PeregenerateMap",
		"При перегенерации карты, с карты будут удалены все постройки и декорации.\n После перегенерации карту нельзя восстановить!",
		"When the map is regenerated, all buildings and scenery will be deleted from the map.\nAfter the regeneration card cannot be restored!",
		"PURCHASE_AUTUMN",
		"Осень",
		"Autumn",
		"SC_MAP_BIOM",
		"Биомы",
		"Bioms",
		"PlayerConnect1",
		"Игрок ",
		"Игрок ",
		"PlayerConnect2",
		" зашел на карту",
		" зашел на карту",
		"PlayerDisconnect1",
		"Игрок ",
		"Игрок ",
		"PlayerDisconnect2",
		" покинул карту",
		" покинул карту",
		"PURCHASE_RUN_MAP",
		"Лавовая",
		"Lava",
		"PURCHASE_PLATFORM_MAP",
		"Платформа",
		"Platform",
		"MAP_TYPE_LAVA",
		"Лавовая",
		"Lava",
		"MAP_TYPE_PLATFORM",
		"Платформа",
		"Platform",
		"START_FAST_GAME",
		"БЫСТРАЯ ИГРА",
		"FAST GAME",
		"START_MY_MAPS",
		"МОИ КАРТЫ",
		"MY MAPS",
		"START_SERVERS_LIST",
		"СПИСОК СЕРВЕРОВ",
		"SERVERS LIST",
		"INVITE_FRENDS",
		"ПОЗВАТЬ ДРУЗЕЙ",
		"INVITE FRENDS",
		"ChangeWorld",
		"Сменить мир",
		"Change world",
		"ChangeNick",
		"Сменить ник",
		"Change nick",
		"MAP_SIZE_TINY",
		"Маленькая",
		"Small",
		"MAP_SIZE_SMALL",
		"Стандарт",
		"Standart",
		"MAP_SIZE_MEDIUM",
		"Средняя",
		"Medium",
		"MAP_SIZE_LARGE",
		"Большая",
		"Large",
		"NY",
		"Новый год",
		"Christmas",
		"DECOR_MIDLE_AGE",
		"Замок",
		"Castle Decorations",
		"Improvements",
		"Улучшения",
		"Improvements",
		"PURCHASE_TELEPORT",
		"Зелье телепортации",
		"Potion of teleportation",
		"PURCHASE_SPEED_POTION",
		"Зелье скорости",
		"Swiftness Potion",
		"PURCHASE_FLIGHT_POTION",
		"Зелье полета",
		"Potion of flight",
		"PURCHASE_TINY_MAP",
		"Маленькая карта",
		"Small map",
		"PURCHASE_MIDDLE_MAP",
		"Средняя карта",
		"Middle map",
		"PURCHASE_LARGE_MAP",
		"Большая карта",
		"Large map",
		"PURCHASE_MUSH_WHITE",
		"Белый гриб",
		"Porcini",
		"PURCHASE_MUSH_FOX",
		"Лисички",
		"Chanterelles",
		"PURCHASE_MUSH_AMANITA",
		"Мухоморы",
		"Amanita",
		"PURCHASE_MUSH_ORANGE_CAP",
		"Подосиновики",
		"Leccinum",
		"PURCHASE_MUSH_TOADSTOOL",
		"Поганки",
		"Toadstools",
		"PURCHASE_DESC_TINY_MAP",
		"Размер карты: 64x64",
		"Map size: 64x64",
		"PURCHASE_DESC_MIDDLE_MAP",
		"Размер карты: 192x192",
		"Map size: 192x192",
		"PURCHASE_DESC_LARGE_MAP",
		"Размер карты: 256x256",
		"Map size: 256x256",
		"PURCHASE_DESC_IMPROVED_PICK",
		"Блоки разрушаются в 2 раза быстрее",
		"Blocks are destroyed 2 times faster",
		"PURCHASE_DESC_SUPER_KIRCKA",
		"Блоки разрушаются с 1 удара",
		"Blocks are destroyed with 1 blow",
		"Beach",
		"Пляж",
		"Beach",
		"School",
		"Школа",
		"School",
		"Camping",
		"Поход",
		"Camping",
		"Halloween",
		"Хэллоуин",
		"Halloween",
		"Western",
		"Вестерн",
		"Western",
		"East",
		"Восток",
		"East",
		"Pirates",
		"Пираты",
		"Pirates",
		"key1001",
		"Войти",
		"Enter",
		"key1002",
		"Пароль",
		"Password",
		"key1003",
		"неверный пароль",
		"incorrect password",
		"key2001",
		"NPC",
		"NPC",
		"key2002",
		"Улучшения",
		"Improvements",
		"key2003",
		"Фейерверки",
		"Fireworks",
		"key2004",
		"Транспорт",
		"Transport",
		"key2005",
		"Стикеры",
		"Stickers",
		"key2006",
		"Прочее",
		"Other",
		"key2007",
		"Замок",
		"Castle",
		"key2008",
		"Темный Замок",
		"Dark Castle",
		"key2009",
		"Еда",
		"Food",
		"key2010",
		"Картины",
		"Paintings",
		"key2011",
		"Ковры",
		"Carpets",
		"key2012",
		"Квартира",
		"Apartments",
		"key2013",
		"Город",
		"City",
		"key2014",
		"Военная база",
		"Military",
		"key2015",
		"Типы блоков",
		"Block types",
		"key2016",
		"Сеты блоков",
		"Block sets",
		"key2017",
		"Формы блоков",
		"Forms of blocks",
		"key2018",
		"Цветные блоки",
		"Color blocks",
		"key2019",
		"Лучник",
		"Archer",
		"key2020",
		"Рыцарь",
		"Knight",
		"key2021",
		"Флаги",
		"Flags",
		"key2022",
		"Грибы",
		"Mushrooms",
		"key2023",
		"Комнатные",
		"Houseplants",
		"key3000",
		"Аккаунт заблокирован",
		"Account is banned",
		"key3001",
		"Стоимость разблокировки 12 голосов",
		"The cost of unlocking 12 votes",
		"key3002",
		"Разбан",
		"Unban",
		"key4001",
		"Превышен лимит декораций на карте. Для установки новых декораций удалите ненужные декорации",
		"Exceeded the limit of decorations on the map. To install new decorations, delete unnecessary decorations",
		"key4002",
		"Администратор карты разрешил строить игроку ",
		"Администратор карты разрешил строить игроку ",
		"key4003",
		"Администратор карты запретил строить игроку ",
		"Администратор карты запретил строить игроку ",
		"key4004",
		"Фейерверк может запускать только администратор карты",
		"Firework can only be run the map administrator",
		"key4005",
		"TNT может взрывать только администратор карты",
		"TNT can only be detonate the map administrator",
		"key4006",
		"Авиа бомбу может взрывать только администратор карты",
		"Avia-bomb can only be detonate the map administrator",
		"key4007",
		"Теперь инвентарь открывается клавишей [C]",
		"Now the inventory is opened by pressing the [C]",
		"key5000",
		" монет",
		" coins",
		"key5001",
		"за ",
		"for ",
		"key5002",
		" голоса",
		" votes",
		"key5003",
		" голосов",
		" votes",
		"key6000",
		"Новый сет декораций!",
		"New decorations set!",
		"key6001",
		"Лучник",
		"Archer",
		"key6002",
		"Повар",
		"Cook",
		"key6003",
		"Зомби",
		"Zombie",
		"key6004",
		"Новый скин!",
		"New skin!",
		"key6005",
		"Дракон",
		"Dragon",
		"key6006",
		"Космос",
		"Space",
		"key6007",
		"Лодка",
		"Boat",
		"key7000",
		"Играть",
		"Play",
		"key7001",
		"магазин",
		"shop",
		"key7002",
		"профиль",
		"profile",
		"key7003",
		"топ карт",
		"top maps",
		"key7004",
		"комьюнити",
		"community",
		"key7005",
		"рейтинг",
		"rating",
		"key7006",
		"достижения",
		"achievements",
		"key7007",
		"настройки",
		"settings",
		"key8000",
		"Премиум игрок",
		"Premium Player",
		"key8001",
		"Нечестный игрок",
		"Bad player",
		"key8002",
		"Участник сообщества",
		"Community member",
		"key9000",
		"Стандарт",
		"Standart",
		"key9001",
		"Плоская",
		"Flat",
		"key9002",
		"Платформа",
		"Platform",
		"key9003",
		"Лавовая",
		"Lava",
		"key1100",
		"Лето",
		"Summer",
		"key1101",
		"Осень",
		"Autumn",
		"key1102",
		"Зима",
		"Winter",
		"key1103",
		"Океан",
		"Okean",
		"key1104",
		"Острова",
		"Islands",
		"key1105",
		"Пустыня",
		"Desert",
		"key1200",
		"В данном режиме нет открытых карт",
		"There are no open maps in this gamemode",
		"key1201",
		"Открыть новую?",
		"Open new?",
		"key1202",
		"Открыть",
		"Open",
		"key1203",
		"Поиск",
		"Search",
		"key1300",
		"Название карты должно содержать не менее трех символов",
		"The map name must contain at least three characters",
		"PURCHASE_FIREWORK1",
		"Красный фейерверк",
		"Red firework",
		"PURCHASE_FIREWORK2",
		"Желтый фейерверк",
		"Yellow firework",
		"PURCHASE_FIREWORK3",
		"Синий фейерверк",
		"Blue firework",
		"PURCHASE_FIREWORK4",
		"Зеленый фейерверк",
		"Green firework",
		"PURCHASE_HOUSEPLANTS1",
		"Фиалка",
		"Violet",
		"PURCHASE_HOUSEPLANTS2",
		"Гербера",
		"Gerbera",
		"PURCHASE_HOUSEPLANTS3",
		"Фикус",
		"Ficus",
		"PURCHASE_HOUSEPLANTS4",
		"Кактус",
		"Cactus",
		"PURCHASE_HOUSEPLANTS5",
		"Розы",
		"Roses",
		"Rivendell",
		"Ривенделл",
		"Rivendell",
		"Forest",
		"Лес",
		"Forest",
		"Midory",
		"Мидори",
		"Midory",
		"Spaceport",
		"Космодром",
		"Spaceport",
		"Office",
		"Офис",
		"Office",
		"Zone69",
		"Зона 69",
		"Zone 69",
		"Kitchen",
		"Кухня",
		"Kitchen",
		"Station",
		"Станция",
		"Station",
		"Factory",
		"Завод",
		"Factory",
		"ConstructionSite",
		"Стройплощадка",
		"Construction site",
		"Storage",
		"Склад",
		"Storage",
		"Firing_field",
		"Полигон",
		"Firing field",
		"Butterfly_death",
		"Бабочка смерти",
		"Butterfly death",
		"Spiral",
		"Спираль",
		"Spiral",
		"EyesOfStruggle",
		"Глаза борьбы",
		"Eyes Of Struggle",
		"Balance",
		"Баланс",
		"Balance",
		"Sun",
		"Солнце",
		"Sun",
		"Rainbow",
		"Радуга",
		"Rainbow",
		"Lines",
		"Линии",
		"Lines",
		"Bricks",
		"Кубики",
		"Bricks",
		"Zigzag",
		"Зигзаг",
		"Zigzag",
		"Round",
		"Кольца",
		"Round",
		"TradeYard",
		"Торговый двор",
		"Trade Yard",
		"Greenwood",
		"Гринвуд",
		"Greenwood",
		"AbandonedLaboratory",
		"Заброшенная лаборатория",
		"Abandoned laboratory",
		"GasStation",
		"Заправка",
		"Gas station",
		"PURCHASE_WSKIN_SG553_FIOL",
		"Дайри",
		"Dairy",
		"PURCHASE_WSKIN_SG553_TREANGLE",
		"Триангл",
		"Triangle",
		"PURCHASE_WSKIN_SG553_CAMO",
		"Камуфляж",
		"Camo",
		"PURCHASE_WSKIN_SG553_DRAGON",
		"Дракон",
		"Dragon",
		"PURCHASE_WSKIN_SG553_SPACE",
		"Космос",
		"Space",
		"PURCHASE_WSKIN_SWD_VORTEX",
		"Вихрь",
		"Vortex",
		"PURCHASE_WSKIN_SWD_RADIATION",
		"Радиация",
		"Radiation",
		"PURCHASE_WSKIN_SWD_LEGACY",
		"Наследие",
		"Legacy",
		"PURCHASE_WSKIN_SWD_GEAR",
		"Механизм",
		"Gear",
		"PURCHASE_WSKIN_SWD_CARBON",
		"Карбон",
		"Carbon",
		"PURCHASE_WSKIN_GLOCK_GEAR",
		"Закат",
		"Sunset",
		"PURCHASE_WSKIN_GLOCK_PIRATE",
		"Пират",
		"Pirate",
		"PURCHASE_WSKIN_GLOCK_BLOOD",
		"Кровь",
		"Blood",
		"PURCHASE_WSKIN_GLOCK_CRIME",
		"Криминал",
		"Crime",
		"PURCHASE_WSKIN_MP5_PALETTE",
		"Палитра",
		"Palette",
		"PURCHASE_WSKIN_MP5_SPRINT",
		"Спринт",
		"Sprint",
		"PURCHASE_WSKIN_MP5_CYBER",
		"Сайбер",
		"Cyber",
		"PURCHASE_WSKIN_MP5_LUXURY",
		"Роскошь",
		"Luxury",
		"PURCHASE_WSKIN_AK47_BLUE",
		"Лазурит",
		"Lazurit",
		"PURCHASE_WSKIN_AK47_WASTELAND",
		"Пустошь",
		"Wasteland",
		"PURCHASE_WSKIN_AK47_MAGMA",
		"Магма",
		"Magma",
		"PURCHASE_WSKIN_AK47_VULK",
		"Бриз",
		"Breeze",
		"PURCHASE_WSKIN_M16_KHAKI",
		"Джунгли",
		"Jungle",
		"PURCHASE_WSKIN_M16_ICEBERG",
		"Айсберг",
		"Iceberg",
		"PURCHASE_WSKIN_M16_AZIMOV",
		"Анисимов",
		"Anisimov",
		"PURCHASE_WSKIN_M16_RIDGIE",
		"Риджи",
		"Ridgie",
		"PURCHASE_WSKIN_SG550_PIXEL",
		"Пиксель",
		"Pixel",
		"PURCHASE_WSKIN_SG550_FUTURE",
		"Будущее",
		"Future",
		"PURCHASE_WSKIN_SG550_NEON",
		"Неон",
		"Neon",
		"PURCHASE_WSKIN_SG550_GLORY",
		"Триумф",
		"Glory",
		"PURCHASE_WSKIN_M1014_DAYME",
		"Гранит",
		"Granite",
		"PURCHASE_WSKIN_M1014_RED",
		"Пламя",
		"Flame",
		"PURCHASE_WSKIN_AUG_TIMBER",
		"Лесной",
		"Timber",
		"PURCHASE_WSKIN_AUG_WAVES",
		"Волны",
		"Waves",
		"PURCHASE_WSKIN_SAWN_OFF_ORIGAMI",
		"Оригами",
		"Origami",
		"PURCHASE_WSKIN_GLAUNCHER_SAKURA",
		"Сакура",
		"Sakura",
		"PURCHASE_NPC1",
		"NPC Повар",
		"NPC Cook",
		"PURCHASE_NPC2",
		"NPC Кузнец",
		"NPC Smelter",
		"PURCHASE_NPC3",
		"NPC Железный копатель",
		"NPC Iron digger",
		"PURCHASE_NPC4",
		"NPC Темный копатель",
		"NPC Dark digger",
		"PURCHASE_NPC5",
		"NPC Дигпул",
		"NPC Digpool",
		"PURCHASE_NPC6",
		"NPC Санта",
		"NPC Santa",
		"PURCHASE_NPC7",
		"NPC Пират",
		"NPC Pirate",
		"PURCHASE_NPC8",
		"NPC Капитан пиратов",
		"NPC Captain Pirate",
		"PURCHASE_NPC9",
		"NPC Доктор",
		"NPC Doctor",
		"PURCHASE_NPC10",
		"NPC Пожарный",
		"NPC Firefighter",
		"PURCHASE_NPC11",
		"NPC Полицейский",
		"NPC Policeman",
		"PURCHASE_NPC12",
		"NPC Советский солдат",
		"NPC Soviet soldier",
		"PURCHASE_NPC13",
		"NPC Американский солдат",
		"NPC USA soldier",
		"PURCHASE_NPC14",
		"NPC Немецкий солдат",
		"NPC German officer",
		"PURCHASE_NPC15",
		"NPC Террорист",
		"NPC Terrorist",
		"PURCHASE_NPC16",
		"NPC Спецназ",
		"NPC SWAT",
		"PURCHASE_NPC17",
		"NPC Зомби",
		"NPC Zombie",
		"PURCHASE_NPC18",
		"NPC Рыцарь",
		"NPC Knight",
		"PURCHASE_NPC19",
		"NPC Эпичный Рыцарь",
		"NPC Epic Knight",
		"PURCHASE_FLAG1",
		"Флаг США",
		"Flag USA",
		"PURCHASE_FLAG2",
		"Флаг Россия",
		"Flag Russia",
		"PURCHASE_FLAG3",
		"Флаг Украина",
		"Flag Ukraine",
		"PURCHASE_FLAG4",
		"Флаг Беларусь",
		"Flag Belarus",
		"PURCHASE_FLAG5",
		"Флаг Италия",
		"Flag Italy",
		"PURCHASE_FLAG6",
		"Флаг Бразилия",
		"Flag Brazil",
		"PURCHASE_FLAG7",
		"Флаг Великобритания",
		"Flag Great Britain",
		"PURCHASE_FLAG8",
		"Флаг Германия",
		"Flag Germany",
		"PURCHASE_FLAG9",
		"Флаг Казахстан",
		"Flag Kazakhstan",
		"PURCHASE_FLAG10",
		"Флаг Япония",
		"Flag Japan",
		"PURCHASE_FLAG11",
		"Флаг Пиратов",
		"Flag Pirates",
		"PURCHASE_FLAG12",
		"Флаг СССР",
		"Flag USSR",
		"PURCHASE_BEACH1",
		"Шезлонг",
		"Deck chair",
		"PURCHASE_BEACH2",
		"Замок из песка",
		"Sand castle",
		"PURCHASE_BEACH3",
		"Серфборд",
		"Surfboard",
		"PURCHASE_BEACH4",
		"Спасательный круг",
		"Lifebuoy",
		"PURCHASE_BEACH5",
		"Полотенце",
		"Towel",
		"PURCHASE_BEACH6",
		"Мяч",
		"Ball",
		"PURCHASE_SCHOOL1",
		"Доска",
		"Board",
		"PURCHASE_SCHOOL2",
		"Учебники",
		"Schoolbooks",
		"PURCHASE_SCHOOL3",
		"Стул",
		"Chair",
		"PURCHASE_SCHOOL4",
		"Парта",
		"Desk",
		"PURCHASE_SCHOOL5",
		"Рюкзак",
		"Backpack",
		"PURCHASE_SCHOOL5_YELLOW",
		"Желтый рюкзак",
		"Yellow backpack",
		"PURCHASE_SCHOOL5_RED",
		"Красный рюкзак",
		"Red backpack",
		"PURCHASE_SCHOOL5_BLUE",
		"Синий рюкзак",
		"Blue backpack",
		"PURCHASE_SCHOOL6",
		"Глобус",
		"Globe",
		"PURCHASE_CAMPING1",
		"Палатка",
		"Tent",
		"PURCHASE_CAMPING1_BLUE",
		"Синяя палатка",
		"Blue tent",
		"PURCHASE_CAMPING1_YELLOW",
		"Желтая палатка",
		"Yellow tent",
		"PURCHASE_CAMPING1_GREEN",
		"Зеленая палатка",
		"Green tent",
		"PURCHASE_CAMPING2",
		"Костер",
		"Campfire",
		"PURCHASE_CAMPING3",
		"Котелок",
		"Cauldron",
		"PURCHASE_CAMPING4",
		"Рюкзак",
		"Backpack",
		"PURCHASE_CAMPING5",
		"Раскладной стул",
		"Folding chair",
		"PURCHASE_CAMPING6",
		"Дрова",
		"Firewood",
		"PURCHASE_HALLOWEEN1",
		"Паутина",
		"Web",
		"PURCHASE_HALLOWEEN2",
		"Надгробие",
		"Tombstone",
		"PURCHASE_HALLOWEEN3",
		"Котелок",
		"Cauldron",
		"PURCHASE_HALLOWEEN4",
		"Тыква",
		"Pumpkin",
		"PURCHASE_HALLOWEEN5",
		"Глазастая склянка",
		"Eyed flask",
		"PURCHASE_HALLOWEEN6",
		"Череп",
		"Skull",
		"PURCHASE_WESTERN1",
		"Вывеска",
		"Signboard",
		"PURCHASE_WESTERN2",
		"Бычий череп",
		"Bull skull",
		"PURCHASE_WESTERN3",
		"Кактус",
		"Cactus",
		"PURCHASE_WESTERN4",
		"Стог сена",
		"Hay stack",
		"PURCHASE_WESTERN5",
		"Фонарь",
		"Lantern",
		"PURCHASE_WESTERN6",
		"Колесо",
		"Wheel",
		"PURCHASE_WESTERN7",
		"Плакат",
		"Poster",
		"PURCHASE_NY3",
		"Фейерверк",
		"Firework",
		"PURCHASE_NY4_BLUE",
		"Подарок",
		"Gift",
		"PURCHASE_NY4_GREEN",
		"Подарок",
		"Gift",
		"PURCHASE_NY9",
		"Тедди",
		"Teddy",
		"PURCHASE_NY10",
		"Мишура",
		"Tinsel",
		"PURCHASE_NY11",
		"Свеча",
		"Candle",
		"PURCHASE_NY12",
		"Имбирный пряник",
		"Gingerbread",
		"PURCHASE_NY12_DIGGER",
		"Имбирный пряник",
		"Gingerbread",
		"PURCHASE_NY12_HOUSE",
		"Имбирный пряник",
		"Gingerbread",
		"PURCHASE_NY12_TREE",
		"Имбирный пряник",
		"Gingerbread",
		"PURCHASE_NY12_SNOWFLAKE",
		"Имбирный пряник",
		"Gingerbread",
		"PURCHASE_EAST1",
		"Фонарь",
		"Lantern",
		"PURCHASE_EAST2",
		"Катана",
		"Katana",
		"PURCHASE_EAST3",
		"Сакура",
		"Sakura",
		"PURCHASE_EAST4",
		"Веер",
		"Fan",
		"PURCHASE_EAST5",
		"Свиток",
		"Scroll",
		"PURCHASE_EAST6",
		"Картина",
		"Picture",
		"PURCHASE_EAST6_BLACK",
		"Черная картина",
		"Black picture",
		"PURCHASE_EAST6_WHITE",
		"Белая картина",
		"White picture",
		"PURCHASE_PIRATES1",
		"Якорь",
		"Anchor",
		"PURCHASE_PIRATES2",
		"Ящик",
		"Box",
		"PURCHASE_PIRATES3",
		"Пушка",
		"Cannon",
		"PURCHASE_PIRATES4",
		"Спасательный круг",
		"Lifebuoy",
		"PURCHASE_PIRATES5",
		"Штурвал",
		"Steering  Wheel",
		"PURCHASE_PIRATES6",
		"Сундук сокровищ",
		"Treasure Chest",
		"PURCHASE_POLICEMAN_GIRL",
		"Девушка полицейский",
		"Girl policeman"
	};

	public enum LocaleType
	{
		RU,
		EN
	}

	public enum MounthCase
	{
		ACCUSATIVE
	}
}
